### ISSUE TITLE
Bootstrap 4 Changes that cause this plug in to fail

### ISSUE THREAD

**Issue by Modicrumb** [FriendsOfCake/bootstrap-ui#103]
We should focus on opening a new branch to prepare for the future:

Details can be seen here: http://v4-alpha.getbootstrap.com/migration/#forms

Bootstrap 4 failing with this plug in can be demoed here:
http://sandbox3.dereuromark.de/sandbox/bootstrap

In the Demo none of the bootstrap 4 js is included as of currently. The minified bootstrap css is however included and can be seen to not work with current plug in since bootstrap decided to change some class names.

**Comment by ADmad** [comment]
It's still alpha which means things can change. We can give it a serious look once beta / RC is out.

**Comment by steefaan** [comment]
@Modicrumb you can reconfigure the FormHelper just a bit an it also works with Bootstrap4. I do it on the same way. It's not the cleanest approach but if you want to work with Bootstrap4 it's an option.

**Comment by jadb** [comment]
@steefaan, when you have time, if you can provide your changes as a gist, would help others (and us when comes time to add support for it).

Just sayin' :wink:

**Comment by steefaan** [comment]
@jadb Sorry I'm really under time presure currently but I will provide something as soon as possible.

**Comment by Modicrumb** [comment]
This worked for me for forms, the datetime widget still doesn't work since they removed all css stylings that are nested like .foo > li
https://github.com/Modicrumb/bootstrap-ui/commit/41d0642cd9bfcbe000a18cd383b813b44ae35e20,
maybe we can include a version parameter in the view and start setting things up for bootstrap 4 based on that parameter?

**Comment by steefaan** [comment]
@jadb @Modicrumb I will provide another plugin soon:

Preview:
![image](https://cloud.githubusercontent.com/assets/5982785/17749313/69ad6e66-64bd-11e6-9306-16395cbb6745.png)

It's completely compiled from PHP through the FormHelper.

Things I need to finish before publish the plugin:
- Form feedbacks
- Buttons
- Test Cases

**Comment by jadb** [comment]
@steefaan, looking good! 

That's a PR you're working on?

**Comment by thinkingmedia** [comment]
4 isn't compatible with 3. There would have to be a new branch dedicated to it. It also requires people to migrate to 4 which is going to a pain for most.

**Comment by ADmad** [comment]
Support for v3 has not ended. They are just going stop actively developing it and concentrate on v4 instead.

Regardless, patches for updating the plugin to support bootstrap v4 are welcome. Currently it seems everyone is waiting for someone to do the work 😀
