### ISSUE TITLE
RFC, Depending on Bootstrap

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/bootstrap-ui#114]
As there is a repo for it on Packagist.
https://packagist.org/packages/twbs/bootstrap

Should the plugin either `require` it, or `suggest` it and provide a shell task to symlink the resources into the `webroot/css` folder?

**Comment by ADmad** [comment]
It's pretty uncommon to manage js / css assets through composer.

**Comment by ayman-alkom** [comment]
what about having a bower.json and set the bower component folder to webroot/assets and make en element for the stuff of including them.
I think that every developer has the same issue with initializing the plugin

**Comment by davidyell** [comment]
My problem with Bower is that it comes with a number of dependencies. Bower requires NPM, which requires Node. It would certainly help anyone using Bower already for front-end assets though for sure.

I just feel that the plugin could do with *something* in this area, as including Bootstrap in your plugin is pretty key to making this plugin 'work' in the intended fashion. That might be a Composer suggest, or even just some updates to the readme to appraise users of the possibilities. Whether that be Bowser, Composer or Zip file.

**Comment by ADmad** [comment]
Providing a "suggest" for composer won't do much unless the plugin also provides instructions/shell to copy/link the assets under webroot.

**Comment by ayman-alkom** [comment]
yes @davidyell  you are right about the dependencies of bower, but I meant that we can keep the assets at the webroot, so we dont need to run bower unless who want to update the assets will need the node and NPM

**Comment by jadb** [comment]
I will document how I use it with composer on some setups as a proposed RFC and we shall see what the majority thinks.

/cc @deizel

**Comment by ADmad** [comment]
v2 of the plugin provides a shell which install assets using `npm`. While BS4 and jquery are available through `composer` BS4 also requires `popper.js` which isn't, so it's not feasible to use composer to get install all assets too.
