### ISSUE TITLE
Best way to extend formhelper templates

### ISSUE THREAD

**Issue by aa411853** [FriendsOfCake/bootstrap-ui#116]
What's best way to extend the included FormHelper templates?  For instance if I wanted to add a custom dateFormGroup and dateWidget.

I realize I can handle like this at view level, but I'd prefer to change app wide:

       $templates = [
            'dateFormGroup' => '{{label}}<div class="col-md-8"><div class="input-group date">{{input}}{{error}}{{help}}</div></div>',
            'dateWidget'    => '<input type="text" class="form-control" name="{{name}}" {{attrs}} /><span class="input-group-addon"><span class="fa fa-calendar"></span></span>'
        ];
        $this->Form->templates($templates);

**Comment by ADmad** [comment]
http://book.cakephp.org/3.0/en/views/helpers/form.html#customizing-the-templates-formhelper-uses

**Comment by aa411853** [comment]
Thanks ADmad, yes I understand how to customize the default Cake templates.  But how can I modify the templates created with BootstrapUI FormHelper without touching the source?  

For example to change dateWidget and add dateFormGroup, but leave all other BootstrapUI FormHelper templates the same.

**Comment by jrble819** [comment]
@aa411853 This sounds like the same problem I'm having and submitted a pull request for: #113
