### ISSUE TITLE
Fatal error : Helper class HtmlHelper could not be found.

### ISSUE THREAD

**Issue by YuvPrime** [FriendsOfCake/bootstrap-ui#120]
As per in the read-me, I download the plugin using composer and loaded the plugin using `Plugin::load('BootstrapUI');`

As soon as I add the following lines in AppView.php,

       $this->loadHelper('Html', ['className' => 'BootstrapUI.Html']);
       $this->loadHelper('Form', ['className' => 'BootstrapUI.Form']);
       $this->loadHelper('Flash', ['className' => 'BootstrapUI.Flash']);
       $this->loadHelper('Paginator', ['className' => 'BootstrapUI.Paginator']);

it throws the error **Helper Class xxxxx could not be found**

Latest Version : Cakephp & Bootstrap-UI.

**Comment by josegonzalez** [comment]
> Helper Class xxxxx could not be found

What is the `xxxxx` here?

**Comment by YuvPrime** [comment]
All the helpers described inside initialize() method of AppView.

**Comment by thinkingmedia** [comment]
This works fine for me with latest CakePHP and Bootstrap-UI.

```
<?php

namespace App\View;

use Cake\View\View;

/**
 * @property \BootstrapUI\View\Helper\FlashHelper $Flash
 * @property \BootstrapUI\View\Helper\FormHelper $Form
 * @property \BootstrapUI\View\Helper\HtmlHelper $Html
 * @property \BootstrapUI\View\Helper\PaginatorHelper $Paginator
 */
class AppView extends View
{

    /**
     * Initialization hook method.
     */
    public function initialize()
    {
        parent::initialize();

        $this->loadHelper('Html', ['className' => 'BootstrapUI.Html']);
        $this->loadHelper('Form', ['className' => 'BootstrapUI.Form']);
        $this->loadHelper('Flash', ['className' => 'BootstrapUI.Flash']);
        $this->loadHelper('Paginator', ['className' => 'BootstrapUI.Paginator']);
    }
}
```

Are you calling `loadHelper` from `initialize()`?

**Comment by ADmad** [comment]
Closing as loading of plugin helpers works fine, so there's nothing to be fixed.
