### ISSUE TITLE
Add primary class for the ButtonWidget

### ISSUE THREAD

**Issue by broot02** [FriendsOfCake/bootstrap-ui#122]
The following code `<?= $this->Form->button('Signup', ['class' => 'success'])?>` would produce the following HTML, `<button class="btn-success btn" type="submit">Signup</button>`. This is expected.

But  the following code `<?= $this->Form->button('Signup', ['class' => 'primary'])?>` would produce the following HTML, `<button class="primary btn" type="submit">Signup</button>`. This is not expected in my opinion, rather we should see the css class `btn-primary` added as `btn-success` was added above.

It seems adding 'primary' to `$_styles` in the ButtonWidget would correct this issue, and would give the expected behavior, and allow consistent use of the button widget, and allow the use of standard classes for buttons with Bootstrap.

**Comment by broot02** [comment]
Is this considered an issue? Or do I have incorrect expectations?

**Comment by ADmad** [comment]
Given the inconsistency i would say it is a bug. Would you mind making a pull request fixing the issue.

**Comment by broot02** [comment]
Sure thing.

**Comment by broot02** [comment]
This has been corrected.
