### ISSUE TITLE
Remove the default layout set from the trait

### ISSUE THREAD

**Issue by icaroscherma** [FriendsOfCake/bootstrap-ui#129]
I suggest to remove the lines:
```PHP
if (empty($this->layout) || $this->layout === 'default') {
    $this->layout = 'BootstrapUI.default';
}
```
from `initializeUI()` in the `UIViewTrait`, because doing so you kind of force the user to create another template name and set it into its own `AppView`.
Or change the method to support some args and then enable, like:
```PHP
public function initializeUI(array $args)
{
    if ($args['useBsLayout'] && (empty($this->layout) || $this->layout === 'default')) {
        $this->layout = 'BootstrapUI.default';
    }
}
```
and inside your AppView you pass what you need: `$this->initializeUI(['useBsLayout' => true]);`.
=)

**Comment by ADmad** [comment]
> because doing so you kind of force the user to create another template name and set it into its own AppView

I don't really understand what you mean. If you set a custom layout using viewBuilder() in your controller that will be used else by default 'BootstrapUI.default' will be used.

**Comment by icaroscherma** [comment]
@ADmad in other terms, if you use the trait, you force the user to change the default layout's filename, otherwise it will use bootstrap's. ok, we both said the same thing, but I'm trying to say that this is not a good approach.

In my `default.ctp` layout, I've already put bootstrap's js/css and jquery, I just want to use the helpers from bootstrap-ui's plugin, by using the UIViewTrait the code become cleaner, because we just put one line describing that we want to enable this "resource" (the helpers), but it force me to change the `public $layout` to something else than "default", otherwise `vendor/.../default.ctp` will be used.

The idea behind the bootstrap-ui plugin is the code reuse (DRY), so the user keep using the helper but with bootstrap guidelines already inside it, not force the user to change its behavior, like default filenames.
(I know, this is too simple to change the "default.ctp" to another)

**Comment by ADmad** [comment]
Okay, I understand now :) 

Would you like to make a PR which you proposed change? Should actually also remove the `empty($this->layout)` check and it would prevent rendering a template without layout.
