### ISSUE TITLE
Textarea not implemented

### ISSUE THREAD

**Issue by nicls** [FriendsOfCake/bootstrap-ui#133]
Hello, 

it seems to me that the Form-Element 'textarea' is not implemented!?

Regards,
cls

**Comment by ADmad** [comment]
What did you try?  What did you get? What did you expect?

**Comment by thinkingmedia** [comment]
@nicls Don't use `$this->Form->textarea(...)` instead use `$this->Form->input('name',['type'=>'textarea']);`

This is the same for select options. It would be nice if the helper worked for specific input types.
