### ISSUE TITLE
Bootstrap layout used when rendering cells.

### ISSUE THREAD

**Issue by thinkingmedia** [FriendsOfCake/bootstrap-ui#134]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* bootstrap-ui Version: 0.04
* Target: CakePHP 3.2.3

### What you did

Installed the bootstrap-ui in a project using cells.

### Expected Behavior

Cells should render forms and other elements.

### Actual Behavior

Cells were rendered with contents from `BootstrapUI.default`

The UIViewTrait forces layout usage

```
        if (empty($this->layout) || $this->layout === 'default') {
            $this->layout = 'BootstrapUI.default';
        }
```

I think the problem is that `empty($this->layout)` is greedy. When cells are rendered the CakePHP framework assigns `$this->layout = false` but then bootstrap-ui sets the layout anyway.

**Comment by ADmad** [comment]
Cells are always rendered [without a layout](https://github.com/cakephp/cakephp/blob/master/src/View/Cell.php#L201), so layout set by UIViewTrait is irrelevant.

**Comment by ADmad** [comment]
Sorry I misread, this does look like a problem.

**Comment by ADmad** [comment]
The code you have referenced has already been changed. Can you please test against the master branch and check if issue still exists?

**Comment by ADmad** [comment]
PR for fix opened.

**Comment by thinkingmedia** [comment]
wow. I was not expecting such a quick fix. Thank you.
