### ISSUE TITLE
Paginator Template not changing the template on-the-fly (Inside View)

### ISSUE THREAD

**Issue by icaroscherma** [FriendsOfCake/bootstrap-ui#137]
Things like this (code below), are not working:

`Tests\index.ctp`
```php
<?php
    $this->Paginator->templates([
        'sortAsc' => '<a class="sorting_asc" href="{{url}}">{{text}}</a>',
        'sortDesc' => '<a class="sorting_desc" href="{{url}}">{{text}}</a>'
    ]);
?>
```

We need to put the template at the Component, not the Helper. It's lacking this feature.

**Comment by ADmad** [comment]
> We need to put the template at the Component, not the Helper.

Not sure what you mean. Component have nothing to do with string template which belong in view layer.

BootstrapUI's PaginatorHelper does not modify the templates for `sortAsc` and `sortDesc` so I doubt whatever issue you have is related to this plugin.

**Comment by icaroscherma** [comment]
Following [Cake3's Paginator Helper](http://api.cakephp.org/3.2/class-Cake.View.Helper.PaginatorHelper.html#_templates), you should be able to set a template on-the-fly (in the Template, like `index.ctp`), like in the code sent in previous description. But when I try to do that way, it changes nothing.
If I try to change in my `AppView.php` and set it in "load-time", it works.
```PHP
<?php
$this->loadHelper(
    'Paginator',
    [
        'className' => 'BootstrapUI.Paginator', 
        'templates' => [
            'sortAsc' => '<a class="sorting_asc" href="{{url}}">{{text}}</a>',
            'sortDesc' => '<a class="sorting_desc" href="{{url}}">{{text}}</a>'
        ]
    ]
);
?>
```

**Comment by ADmad** [comment]
Are you able to change templates on fly with you use core's  `PaginatorHelper` instead of `BootstrapUI.Paginator` ?

**Comment by dereuromark** [comment]
This could indeed be a Core issue instead.

**Comment by icaroscherma** [comment]
The problem was happening because I was setting the property `templates` in my `index.ctp`, and inside of it (`index.ctp`), I was using `element()` to render my table to be paginated (ajax purposes), to get it to work I had to add the `$this->Paginator->templates()` inside the ctp file of the requested element.

Like:
`index.ctp`
```PHP
        <div id="table-paging">
            <?= $this->element('../FatoRegistrosContabeis/datatable') ?>
        </div>
<?php
    $this->Html->scriptStart(['block' => true]);
    echo "
$(document).ready(function() {
    $(document).on('click', '#table-paging a', function () {
        var thisHref = $(this).attr('href');
        if (!thisHref) {
            return false;
        }
        // $('#table-paging').fadeTo(300, 0);
        $('#table-paging').load(thisHref, function() {
        //     $(this).fadeTo(200, 1);
        });
        return false;
    });
});";
    $this->Html->scriptEnd();
?>
```

`element.ctp`
 ```PHP
<?php
    $this->Paginator->templates([
        'sortAsc' => '<a class="sorting_asc" href="{{url}}">{{text}}</a>',
        'sortDesc' => '<a class="sorting_desc" href="{{url}}">{{text}}</a>',
        'ellipsis' => '<a href="" class="btn disabled">...</a>',
        'prevActive' => '<a href="{{url}}" class="btn">&laquo;</a>',
        'prevDisabled' => '<a href="{{url}}" class="btn disabled">&laquo;</a>',
        'nextActive' => '<a href="{{url}}" class="btn">&raquo;</a>',
        'nextDisabled' => '<a href="{{url}}" class="btn disabled">&raquo;</a>',
        'first' => '<a href="{{url}}" class="btn">&laquo;&laquo; </a>',
        'last' => '<a href="{{url}}" class="btn">&raquo;&raquo;</a>',
        'number' => '<a href="{{url}}" class="btn">{{text}}</a>',
        'current' => '<a href="{{url}}" class="btn btn-raised">{{text}}</a>'
    ]);
?>
<table>...</table>

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="btn-group btn-group-justified bs-paging">
            <?= $this->Paginator->first() ?>
            <?= $this->Paginator->prev() ?>
            <?= $this->Paginator->numbers(['before' => '', 'after' => '']) ?>
            <?= $this->Paginator->next() ?>
            <?= $this->Paginator->last() ?>
        </div>
    </div>
</div>
```

I thought that I could set anywhere in the "View" that I was going to use and the Helper would change recursively inside another elements that I render. But it seems that is not like this that is works, I don't know if it is  intended or not.
