### ISSUE TITLE
[question] horizontal forms 'right' grid content

### ISSUE THREAD

**Issue by waspinator** [FriendsOfCake/bootstrap-ui#139]
The FormHelper for horizontal forms has a `grid` property with `left`, `middle`, and `right` options.

```
'grid' => [
                'left' => 2,
                'middle' => 6,
                'right' => 4
            ],
```

`left` is usally used for the label, `middle` for the value. Is `right` supposed to be used for something? Is there a way to add content to it?

**Comment by jadb** [comment]
Nice catch! It [isn't currently being used](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L441) AFAICT. 

The initial idea behind it was to get the errors and/or tips to show there.

**Comment by waspinator** [comment]
That's what I wanted to use it for actually. Too bad it's not implemented. Thanks.
