### ISSUE TITLE
FormHelper->button() should set btn-default

### ISSUE THREAD

**Issue by thinkingmedia** [FriendsOfCake/bootstrap-ui#143]
```
    echo $this->Form->button('Sign In');
```

Above outputs

```
    <button type="submit" class="btn">Sign In</button>
```

Should be outputting with `btn-default`.

```
    <button type="submit" class="btn btn-default">Sign In</button>
```

But it should be smart enough to know when not to include it.

```
    echo $this->Form->button('Sign In',['class'=>'primary']);
```

Should output with `btn-primary` and not `btn-default`.

```
    <button type="submit" class="btn btn-primary">Sign In</button>
```

Since this could impact previous versions. I wanted to verify this was okay before doing a PR.

**Comment by ADmad** [comment]
We could add `btn-default` is `$options['class']` is empty. I doubt anyone would want to generate button with just `btn` class so it shouldn't impact existing users.

**Comment by thinkingmedia** [comment]
great. I'll do a PR for it.
