### ISSUE TITLE
Adding classes to select inputs is not possible

### ISSUE THREAD

**Issue by martonmiklos** [FriendsOfCake/bootstrap-ui#155]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)

The following code:
`echo $this->Form->input('import_bom.col', ['type' => 'select', 'class' => 'foobar']);`

renders
`<div class="form-group select"><label for="import-bom-col">Col</label><select id="import-bom-col" class="form-control" name="import_bom[col]"></select></div>`

Which is bad if you would like to add your own class to the input. I have fixed it, and will came up with a PR soon. (Or later.)

**Comment by dereuromark** [comment]
We are looking forward to your PR!

**Comment by dereuromark** [comment]
@martonmiklos Ping

**Comment by ADmad** [comment]
We has [test case](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/tests/TestCase/View/Helper/FormHelperTest.php#L103) showing that generating select tag with extra class works as expected.
