### ISSUE TITLE
Form Helper generates unexpected html

### ISSUE THREAD

**Issue by KingLoui** [FriendsOfCake/bootstrap-ui#161]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
- BootstrapUI Version: 0.5.1
- Bootstrap Framework Version: 3.3.7
- jQuery: 3.1.1
- CakePHP: 3.3
### What you did

I'm using a commercial bootstrap theme (inspinia) and try to create a basic horizontal form.

```
<?= $this->Form->create(${$tableAlias}, ['align' => [
        'sm' => [
            'left' => 2,
            'middle' => 10,
            'right' => 12
        ],
        'md' => [
            'left' => 2,
            'middle' => 10,
            'right' => 4
        ]
    ]]); ?>
    <?= $this->Form->input('username'); ?>
    <?= $this->Form->input('email'); ?>
    <?= $this->Form->input('password'); ?>
    <?= $this->Form->input('first_name'); ?>
    <?= $this->Form->input('last_name'); ?>
    <?= $this->Form->input('active', ['type' => 'checkbox']); ?>
    <?= $this->Form->submit('Save', ['class' => 'btn-primary']); ?>
 <?= $this->Form->end() ?>
```

the generated html of all inputs is as expected except of the submit button.
### Expected Behavior

This should be generated:

```
<div class="form-group">
    <div class="col-sm-offset-2 col-md-offset-2 col-sm-10 col-md-10">
        <input type="submit" class="btn btn-primary" value="Save">
    </div>
</div>
```
### Actual Behavior

The generated  html output for the submit button

```
<div class="col-sm-offset-2 col-md-offset-2 col-sm-10 col-md-10">
<input type="submit" class="btn btn-primary" value="Save">
</div>
```

The examples on the official bootstrap site also says that there should be a form-group wrapper.
http://getbootstrap.com/css/#forms-horizontal

The issue I'm having is that because there is no wrapper I have to put a clear fix at the and of the form because the grid wrapper is floating.

**Comment by dereuromark** [comment]
I agree with you there, it should for consistency have the same wrapper.
We have to find a way to also allow disabling, or grouping in case you want to have several of those buttons (like submit + cancel) there in a row.

**Comment by ADmad** [comment]
It's better to use `FormHelper::button()` and take care of the wrapping div yourself :)

**Comment by dereuromark** [comment]
@ADmad I gave it a try. Unfortunately, button doesnt wrap it with any of the col-... elements, putting it to the far left:

    <button type="submit" class="btn btn-default">Save</button>

That doesn't look good, either.
Maybe button should then get the col div + a group wrapper by default?
After all, the default plugin methods should render a well gridded form, especially for the baked defaults.
And then, once customized (`'div' => false`?), one achieve more, like multiple buttons etc.

**Comment by ADmad** [comment]
Yes the button doesn't have any wrapping div because the core `FormHelper::button()` doesn't generate a wrapper either.

**Comment by dereuromark** [comment]
Yeah, but the bootstrap plugin helper should append whatever necessary to have a good "form grid" by default IMO.
Maybe we can come up with something that is doing this while staying BC here for the rest.

**Comment by LiaraAlis** [comment]
This problem has affected me today and that is a annoying problem.
Is there a problem to add the `form-group` container in the `submitContainer` template until we have a solution to add more than one button in a row? Currently it is also not possible to disable the row classes.
