### ISSUE TITLE
render a message template throws MissingElementException

### ISSUE THREAD

**Issue by MathRat** [FriendsOfCake/bootstrap-ui#166]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: latest
* Bootstrap Framework Version: 3.3.5
* jQuery: 1.11.3

### What you did
`<?php echo $this->Flash->render('auth', ["element" => "error"]); ?>`

I just wanted to make my auth flash messages looks like Flash->error() messages.

**Comment by ADmad** [comment]
Just use `<?= $this->Flash->render('auth'); ?>`.  The FlashHelper provided in this plugin will automatically show the error message in red using the default flash template.

**Comment by MathRat** [comment]
Flash->error() returns:
`<div role="alert" class="alert alert-dismissible fade in alert-danger"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button> ... </div>`

but Flash->render('auth') returns:
`<div role="alert" class="error"> ... </div>`

and there is no rule in css for showing this in red. what am i doing wrong?

**Comment by dereuromark** [comment]
Check https://github.com/cakephp/cakephp/issues/9614 on how to load the AuthComponent to also use the same error template as the other error flash messages.
In 3.4 you can then remove this part :)
