### ISSUE TITLE
release 1.0.0 stable

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#167]
After the recent bugs have been fixed we should release a 1.0.0 stable here
I don't think the API will change much, and it would make people more confident into the plugin as it stands now.
Any objections?

**Comment by josegonzalez** [comment]
Can we clear out any existing issues/pull requests before doing so? Or at least triage them for a next release.

**Comment by JelmerD** [comment]
I am wondering. As this plugin requires CakePHP 3.x, why isn't the first version 3.0.0 then?

https://www.cakedc.com/plugin-standard

> Versioning: Versions need to specify their version state, as well as their target framework code base.

**Comment by dereuromark** [comment]
CakeDC version numbers are not related to any other entity and their versioning, so also not FriendsOfCake.

**Comment by JelmerD** [comment]
But don't you agree it is convenient to use the same main version number as Cake? I personally find it very useful to determine if a plugin is going to work for my project.

**Comment by ADmad** [comment]
Matching the plugin version with CakePHP version doesn't bring any value. For e.g. in the near feature we might have a new version of the plugin with bootstrap 4 compatibility which would require bumping plugin version to 4.0.0. In the meantime CakePHP version would very likely still be 3.x so version number parity would be lost any way.

**Comment by dereuromark** [comment]
> don't you agree it is convenient to use the same main version number as Cake

I do agree to some extend. But only if done right. I call it [framework semantic versioning](http://www.dereuromark.de/2016/01/29/developing-cakephp-3-plugins-its-fun/#framework-semantic-versioning) - which you can see I blocked about a year ago.
In that case you need a 4 digit versioning: `x.major.minor.patch`

But as long as this is not done across the whole ecosystem, doing it only for a single plugin doesn't make it less confusing ;)

**Comment by JelmerD** [comment]
Quote from your article:

> In theory you could also use a 4th digit

So, why do you say "you need a 4 digit versioning" in your comment?

I just clicked randomly in the https://plugins.cakephp.org/ library, and found a couple of plugins which do the same:

- https://github.com/FriendsOfCake/CakePdf/releases
- https://github.com/markstory/asset_compress/releases
- https://github.com/josegonzalez/cakephp-upload/releases

Especially the first one I find interesting, as it's of FoC as well :) See the 3.0.0 release, so it bumped from 1.0.3 to 3.0.0.

But you have a fair point, not everybody does it. But as FoC, CakeDC, MarkStory and CakePHP are (in my opinion) the most trusted and often show good examples of plugins, I think it's good do draw a line and just say: well, the first number, is always the same as the cake number. 

Others will adapt  (as I did recently as well https://github.com/JelmerD/TableHelper/releases)

**Comment by dereuromark** [comment]
Didn't you read the comment from @ADmad and the issues if you don't do it?
All of your claimed resources use the 3 digit system which as already stated a few times now will get you in trouble when used this way (the wrong way). Also none of the sources properly document the usage of a 4 digit one and how people can expect it to work.
So no, not a single one so far uses framework semantic versioning.

**Comment by JelmerD** [comment]
@dereuromark Sorry, I got a notification from Github linking to your comment. So my browser scrolled only to your comment. So i didn't see his comment, my apologies :)

I see what you mean. I'll have a closer look at it, thanks for explaining 👍

**Comment by ADmad** [comment]
1.0.0 released.
