### ISSUE TITLE
Default form does not add bootstrap class to label when showing selectbox

### ISSUE THREAD

**Issue by steffex** [FriendsOfCake/bootstrap-ui#169]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: v0.5.1
* Bootstrap Framework Version: v3.3.7
* jQuery: v2.1.1
* Platform and Target: Ubuntu 16.04, nginx 1.10.0, CakePHP 3.3.10

### What you did
I've added a default form no extra params and added a selectbox using `input()` method.
```php
echo $this->Form->input('contact_id', ['label' => __('Contact'), 'options' => $contacts]);
```

### Expected Behavior
```html
<div class="form-group select">
    <label class="form-control" for="contact-id">Contact</label>
    <select name="contact_id" id="contact-id" class="form-control">
        <option value="1" selected="selected">Contact 1</option>
        <option value="2">Contact 2</option>
    </select>
</div>   
```

I expect the label to have the class `control-label`.

### Actual Behavior
```html
<div class="form-group select">
    <label for="contact-id">Contact</label>
    <select name="contact_id" id="contact-id" class="form-control">
        <option value="1" selected="selected">Contact 1</option>
        <option value="2">Contact 2</option>
    </select>
</div>   
```

The label is missing the class `control-label`

**Comment by steffex** [comment]
If desired, I can make a pull request if someone can point me in the right direction as to where I can change this template

**Comment by ADmad** [comment]
The basic form example on http://getbootstrap.com/css/ does not show any class `control-label` or otherwise for label tags.

**Comment by steffex** [comment]
Agreed, but in order to highlight the label when the form-group has an error it is required.

see: http://getbootstrap.com/css/#forms-control-validation

**Comment by ADmad** [comment]
I see. It seems `control-label` in already added in case of [horizontal](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L56) form, so you can make a pull request by just moving that label template to `$_templates` itself and updating test cases to reflect the change.

**Comment by dereuromark** [comment]
@steffex Are you able to make a PR here?

**Comment by steffex** [comment]
@dereuromark i'm having some trouble making it work in a way that it doesn't break other elements (including the tests)
