### ISSUE TITLE
Plugin not present after composer install

### ISSUE THREAD

**Issue by andrekat** [FriendsOfCake/bootstrap-ui#178]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: v0.6.0
* Bootstrap Framework Version: not relevant
* jQuery: not relevant
* Platform and Target: windows xampp, php 7.0.16, mysql

### What you did
followed install instructions on readme - installed bootstrap-ui via composer, load plugin via cake helper

### Expected Behavior
plugin working

### Actual Behavior
plugin not working: 

Error: The application is trying to load a file from the BoostrapUI plugin. 

Make sure your plugin BoostrapUI is in the D:\pathtomyserver\one\plugins\ directory and was loaded.

Plugin folder only consists of a file called "empty" - core items are missing i guess?

i appreciate your help!

**Comment by andrekat** [comment]
update: Plugin::loadAll(); fixed this issue - but im not sure whats wrong about: 
Plugin::load('BoostrapUI');

..

**Comment by ayman-alkom** [comment]
@andrekat 
:) is **BootsrapUI** and not **BoostrapUI**

**Comment by andrekat** [comment]
ouch - my fault .. layer 8 problem 🙉 
thanks!
