### ISSUE TITLE
FormHelper error with CakePHP 3.3.13

### ISSUE THREAD

**Issue by nifa-dev** [FriendsOfCake/bootstrap-ui#179]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: v0.6.0).
* Bootstrap Framework Version: v3.3.7
* jQuery: v3.1.0
* Platform and Target: CakePHP v3.3.13.

### What you did
In a view, ex: edit.ctp:

`echo $this->Form->input('system_role');`

### Expected Behavior
As 'system_role' is a TINYINT field, CakePHP should render the input as a single checkbox. 

### Actual Behavior
The single checkbox is rendered as it should, except that the following error is also displayed: 

> Notice (8): Undefined index: input [ROOT/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FormHelper.php, line 350]

The error is not present with CakePHP v3.3.12, so the break occurs in the upgrade to v3.3.13.

**Comment by ADmad** [comment]
The changes in https://github.com/cakephp/cakephp/pull/10100 might be the cause of this.

**Comment by agarzon** [comment]
We are facing the same issue since upgraded to 3.3.13

Triggered by
```php
echo $this->Form->input('status');
```
Which is just a boolean with TINYINT.

We rolled back to cakephp 3.3.12 until a fix ni this plugin has been applied.

**Comment by nifa-dev** [comment]
Thanks for the confirmation, I submitted a PR #180.  We're working through a few issues with a test case at the moment.

**Comment by thinkingmedia** [comment]
I just updated to 3.3.13 and hit this bug as well.

```
echo $this->Form->input('remember', [
    'type' => 'checkbox',
    'label' => __d('Users', 'Remember me'),
    'ng-model' => 'rememberMe'
]);
```

Stack:

```
BootstrapUI\View\Helper\FormHelper::_groupTemplate() - ROOT/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FormHelper.php, line 342
Cake\View\Helper\FormHelper::input() - CORE/src/View/Helper/FormHelper.php, line 1063
BootstrapUI\View\Helper\FormHelper::input() - ROOT/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FormHelper.php, line 241
include - APP/Template/Users/login.ctp, line 49
```

Context:

```
$options = [
	'label' => '<input type="hidden" name="remember" value="0"/><label for="remember"><input type="checkbox" name="remember" value="1" ng-model="rememberMe" id="remember">Remember me</label>',
	'error' => '',
	'options' => [
		'type' => 'checkbox',
		'ng-model' => 'rememberMe',
		'prepend' => null,
		'append' => null,
		'required' => false,
		'options' => null,
		'help' => null,
		'templateVars' => [],
		'id' => 'remember',
		'hiddenField' => '_split'
	]
]
$groupTemplate = 'checkboxFormGroup'
```
