### ISSUE TITLE
Compatibility issue with cakephp 3.3.13?

### ISSUE THREAD

**Issue by cewi** [FriendsOfCake/bootstrap-ui#182]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 0.5.2
* Bootstrap Framework Version: 3.3.13
* jQuery: 3.1.1
* Platform and Target: nginx on ubuntu 16.04 LTS

### What you did
upgraded to cakephp 3.3.13.
Now got the following notice/error when testing my application with phpunit:
```
Notice Error: Undefined index: input in [/home/vagrant/Apps/vpa.new/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FormHelper.php, line 342]
```

### Expected Behavior
no errrors 

### Actual Behavior
I changed line 342 of the FormHelper to the code which is in line 1095 of cakephp's own FormHelper:
```
'input' => isset($options['input']) ? $options['input'] : [],
```
As expected, this resolves the error. But I noticed that there are differences between both Formhelpers. So maybe this only a workaround but not the solution of the underlying problem?

**Comment by dereuromark** [comment]
Did you try v0.6? Those should have fixed the issue.

**Comment by ADmad** [comment]
This issue has already been fixed in v0.6.1.  You should always check with latest version of a plugin / lib before posting an issue :)

**Comment by cewi** [comment]
sorry. did "composer update" before but for some it did not fetch last version.

**Comment by Theaxiom** [comment]
I had to remove the package and then reinstall it. It seems they changed their versioning scheme.
