### ISSUE TITLE
Add option to move `<input>` before `<label>` for radios and checkboxes

### ISSUE THREAD

**Issue by waspinator** [FriendsOfCake/bootstrap-ui#186]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* BootstrapUI Version: v0.6.1
* Bootstrap Framework Version: v3.3.7
* jQuery: v3.1.0
* Platform and Target: Firefox 51 on Ubuntu

### What you did
I'm trying to add styled radio and checkbox options using https://github.com/flatlogic/awesome-bootstrap-checkbox. It requires that `<inputs>` be placed outside and before their corresponding `<label>`s. 

    echo $this->Form->input('some.option', ['type' => 'radio', 'options' => ['value']]);

### Expected Behavior

    <div class="form-group">
      <label class="control-label col-sm-6 col-md-3">Option</label>
      <div class="col-sm-6 col-md-5">
        <input name="some[option]" value="" type="hidden">
        <div class="radio">
          <input name="some[option]" value="0" id="some-option-0" type="radio">
          <label for="some-option-0">value</label>
        </div>
      </div>
    </div>

### Actual Behavior

    <div class="form-group radio">
      <label class="control-label col-sm-6 col-md-3">Option</label>
      <div class="col-sm-6 col-md-5">
        <input name="some[option]" value="" type="hidden">
        <div class="radio">
          <label for="some-option-0">
            <input name="some[option]" value="0" id="some-option-0" type="radio">value</label>
        </div>
      </div>
    </div>

**Comment by ADmad** [comment]
By default bootstrap nests input tag inside label for checkbox, so that's what the plugin does. You can override the string templates as required if want something different.
