### ISSUE TITLE
FormHelper::input() deprecated or not?

### ISSUE THREAD

**Issue by Ooypunk** [FriendsOfCake/bootstrap-ui#187]
In the docblock of FormHelper::input(), it says "@deprecated Use control() instead.", but in the examples (https://github.com/FriendsOfCake/bootstrap-ui#basic-form) it says it should be used, no mention of control().

Which one is correct?

**Comment by ADmad** [comment]
Seems updating the README was missed. Would you like to submit a patch to fix that?

**Comment by Spriz** [comment]
Recently got deprecate with 3.€ - I'm sure patch is welcome for the docs! :)
