### ISSUE TITLE
The install process is way too complicated

### ISSUE THREAD

**Issue by notoriousturtle** [FriendsOfCake/bootstrap-ui#193]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* BootstrapUI Version: Latest

### Feature request, easier install process, and easier custom layout install.
Can we have an easy install script or something, such as this:
https://gist.github.com/notoriousturtle/ea0198288ce46580aea09f11b1bfd01b

It would be good if there was an easy way of quickly dropping a new layout into cake as well. So modifying the ctp files used during the generation process. The current problem I see here is, these files are all over the place, and can be very error prone. It also takes a fair bit of time, especially if you're new to the whole process. It would be good if I could drop a new layout in with relative ease. 

Thanks.

**Comment by davidyell** [comment]
What is easy for you would be annoying for me, as I only use the helpers. So I'd have to remove all the automated stuff once it's finished.

Perhaps a shell task which does this would be an option? Perhaps optionally called from composer somehow?

**Comment by davidyell** [comment]
I think the documentation could be improved the help people get up and running quicker.

**Comment by ADmad** [comment]
The next major release with BS4 compatibility is going to have package.json to download all required libs from npm and cake shells to copy/symlink the assets into app's webroot.

**Comment by davidyell** [comment]
So now the plugin depends on Node.js and NPM? That's far from ideal,
especially when Composer could do this.

**Comment by dereuromark** [comment]
depends? no, it can be used with it, but you are not forced to.

**Comment by davidyell** [comment]
That's great. I hope we can provide some install instructions which form a kind of Quick Start, if people just want to install the plugin, their own jQuery, and Bootstrap; then just get started. Without needing all the extras.

This was the issue raised in Slack. That the plugin lacked clear examples of implementation which didn't involve lots of complex extras. I thought I could sort that out, but it seems with such great progress on the Bootstrap 4 version, it's worth waiting for that release.

**Comment by ADmad** [comment]
Installing jQuery and bootstrap's css and js on your own is no different than how you would use any another js/css in your app. Use whatever way you prefer to get your assets and put them in webroot and then link them in layout using helper.

**Comment by davidyell** [comment]
Yes that would be ideal Quick Start docs content

**Comment by ADmad** [comment]
Closing as v2 has a shell to install the assets (using npm).
