### ISSUE TITLE
is tb_sidebar missing from the X folder?

### ISSUE THREAD

**Issue by jeffreyroberts** [FriendsOfCake/bootstrap-ui#196]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: ^1.1
* Bootstrap Framework Version: 3.x?
* jQuery: 2.2.3
* Platform and Target: cake web server, os x, php 5.6.

### What you did
im going over the dashboard example layout, and i am wondering if I am missing something....

### Expected Behavior
I found

            <div class="col-sm-3 col-md-2 sidebar">
                <?= $this->fetch('tb_sidebar') ?>
            </div>

but i didn't find

    tb_sidebar.ctp

### Actual Behavior
is this file missing?

**Comment by ADmad** [comment]
View:: fetch() gets an in memory content block, not an element.
