### ISSUE TITLE
Not compatible with new CakePHP version

### ISSUE THREAD

**Issue by mirorac** [FriendsOfCake/bootstrap-ui#197]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: v0.5.2

### What you did
I have used new [FormHelper::control method](https://book.cakephp.org/3.0/en/views/helpers/form.html#Cake\View\Helper\FormHelper::control)

### Expected Behavior
have support for FormHelper::control

### Actual Behavior
when using FormHelper::control, notice is generated since *help* option is missing because boostrap-ui's form helper *input* method is omitted

![screen shot 2017-07-18 at 11 07 33](https://user-images.githubusercontent.com/8964866/28309783-c4e739d4-6baa-11e7-8960-d770f6413d8e.png)

**Comment by dereuromark** [comment]
Looks like you are terribly outdated: https://github.com/FriendsOfCake/bootstrap-ui/releases
Please use one of the newer (> 0.8) which sure resolved the issue many many months ago.
