### ISSUE TITLE
twitter/bootstrap package integration

### ISSUE THREAD

**Issue by danielzzz** [FriendsOfCake/bootstrap-ui#20]
hi, it would be great if this package used twitter/bootstrap from composer and connected to the styles provided by this package (if possible). thanks. dan

**Comment by danielzzz** [comment]
it might be useful to have the same with jquery and any other dependency, too

**Comment by dakota** [comment]
In my opinion, things like bootstrap, jquery, etc. are better served by using a tool designed for web assets such as bower.

**Comment by AD7six** [comment]
Using composer to install [https://github.com/twbs/bootstrap](bootstrap) might make sense - I'd rather adding this plugin didn't force-include it though as it's making a choice for you.

> it might be useful to have the same with jquery and any other dependency, too

I have never heard of installing jquery (or any other js/css/not-php lib) via compser... do people really do that?

**Comment by ADmad** [comment]
Even if we did include bootstrap as dependency (not that i am in favor of that) it would get installed in vendor directory while cake needs the assets somewhere under webroot. Using bower as @dakota suggested would be a better option.

**Comment by danielzzz** [comment]
I said composer, but yeah, bower would be a better option. 
but the point is, it would be great to have it working out of the package without having to manually add extra files.
Maybe using CDN urls for js and css dependencies would solve this problem.

**Comment by jadb** [comment]
We could add some copy/paste instructions to the README file but the plugin can't (and shouldn't) install bower packages for the end-user.

**Comment by ADmad** [comment]
@jadb Copy / paste instructions sounds good.
