### ISSUE TITLE
FormHelper::staticControl - content not escaped

### ISSUE THREAD

**Issue by aarubui** [FriendsOfCake/bootstrap-ui#202]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

I'm expecting an option to have this line escaped:
https://github.com/FriendsOfCake/bootstrap-ui/blob/fd02bdcd2bb3f58fa7e68c4d770836e0ac9ac988/src/View/Helper/FormHelper.php#L347

**Comment by ADmad** [comment]
Makes sense. Would you like to make a PR adding `escape` option with escaping dine by default?

**Comment by aarubui** [comment]
#203
