### ISSUE TITLE
Tooltip addition

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#204]
This is a (multiple allowed):
* [] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

Currently you can only specify help as text below.
For most grid forms it would be nice however to be able to leverage tooltips after the label text.

E.g.

    echo $this->Form->control('foo', ['tooltip' => 'This is an important info.']);

Which then would be an icon (glyphicon or font-awesome) with title + `rel=tooltip` as bs allows for `.tooltip();` JS:
```html
<label class="control-label col-md-4 col-lg-3">
    Foo <i class="fa fa-info-round" title="This is an important info." rel="tooltip">
</label>...
```

With BS it would be 
```
<span rel="tooltip" title="This is an important info." class="glyphicon glyphicon-info-sign"></span>
```

I guess the labels would have to be adjusted to sth like

    'label' => '<label class="control-label %s"{{attrs}}>{{text}}{{tooltip}}</label>',

And a bit of glue code seems necessary (not sure if as widget or just in the control method).

**Comment by dereuromark** [comment]
I tried https://github.com/FriendsOfCake/bootstrap-ui/compare/feature/tooltips but even though the tooltip itself is rendered well, the part in the label is not filled with it.
I must be missing sth.

**Comment by ADmad** [comment]
Since you want the tooltip inside label it needs to be passed as option for label which isn't happening in your current implementation.

**Comment by dereuromark** [comment]
I haven't worked with the templating yet much.
So I got it working, and

    echo $this->Form->control('foo', ['tooltip' => 'This is an important info.']);

works fine in my application.
But when writing tests, it seems to ignore it for some reason, the result does not contain the expected tooltip HTML..

I pushed the changes to the branch above.

**Comment by dereuromark** [comment]
I debugged and found out that horizontal was what I used and what worked.
The inline one is the label that for some reason loses the placeholders it needs.
It uses the core label config here instead of what I should be using.

**Comment by dereuromark** [comment]
OK, turns out that since it has 3 typs of input, using default you need to also set a "default" custom BS template now. PR open.
