### ISSUE TITLE
Changing default class control-label for label via templateSet

### ISSUE THREAD

**Issue by LubosRemplik** [FriendsOfCake/bootstrap-ui#209]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 1.3.0.

### What you did
```
        $this->loadHelper('Form', [
            'className' => 'BootstrapUI.Form',
            'templateSet' => [
                'horizontal' => [
                    'label' => '<label class="%s"{{attrs}}>{{text}}</label>',
                ]
            ]
        ]);
```

### Expected Behavior
Form label output without `class="control-label"`

### Actual Behavior
Form label output with `class="control-label"`, it ignores templateSet settings. As far as I can see it does merge right config here https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L118 but the code at https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L282 injects class control-label no matter what templateSet we have.

### Workaround
Setting empty class attribute with label template
```
        $this->loadHelper('Form', [
            'className' => 'BootstrapUI.Form',
            'templates' => [
                'label' => '<label class=""{{attrs}}>{{text}}{{tooltip}}</label>',
            ],
        ]);
```

**Comment by ADmad** [comment]
Since you modified the templeset for `horizontal` did you use `FormHelper::create()` with `'align' => 'horizontal'` in options?

**Comment by LubosRemplik** [comment]
I did not, this seems to solve the issue - thanks.  
So when there is no `align` in the `FormHelper::create()` it takes `default` from the list I assume.

But still following code in construct says the `templateSet` should be merged with options I am passing
```
        if (isset($this->_defaultConfig['templateSet'])) {
            $this->_defaultConfig['templateSet'] = Hash::merge($this->_templateSet, $this->_defaultConfig['templateSet']);
        } else {
            $this->_defaultConfig['templateSet'] = $this->_templateSet;
        }
```

So when I load Form Helper like this
```
        $this->loadHelper('Form', [
            'className' => 'BootstrapUI.Form',
            'templateSet' => [
                'horizontal' => [
                    'label' => '<label{{attrs}}>{{text}}</label>',
                ]
            ]
        ]);
```

Is it correct that generated label has `class="control-label"`?

**Comment by LubosRemplik** [comment]
Ignore me, I am stupid. There is horizontal in the templateSet, testing with default

**Comment by LubosRemplik** [comment]
Even with `default` it still injects `class="control-label"` so the bug might not be related to templateSet but to the templates options, when I set

```
'templates' => [
  'label' => '<label{{attrs}}>{{text}}{{tooltip}}</label>',
]
```
There is injected `class="control-label"`, but in my option it should not, only when you do 
```
'templates' => [
  'label' => '<label class="control-label %s"{{attrs}}>{{text}}{{tooltip}}</label>',
]
```
As per horizontal templateSet

**Comment by ADmad** [comment]
Even for default type having the `control-label` class for label is necessary to style the labels based on validation state https://getbootstrap.com/docs/3.3/css/#forms-control-validation
Hence adding  `control-label` by default is a sensible default.

As you stated initially the following achieved what you want, so what's the problem in just using that?
```php
        $this->loadHelper('Form', [
            'className' => 'BootstrapUI.Form',
            'templates' => [
                'label' => '<label class=""{{attrs}}>{{text}}{{tooltip}}</label>',
            ],
        ]);
```
Either way you are going to have to modify the default templates if you don't want the `control-label` class.

**Comment by LubosRemplik** [comment]
Fair enough, will use above as you say :)
Thanks for great plugin. Fell free to close, good for reference though..
