### ISSUE TITLE
BS3 vs BS4 version compatibility of the plugin

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/bootstrap-ui#212]
_From @burzum on April 12, 2018 12:11_

We're in the situation that we have a frontend and a backend. For the backend we've done a theme that will be shared between at least three different management applications we use internally and we want to use BS4 for it.

The issue with that is now that our public website is still using BS3 for the frontend and we don't have any plans to re-work that any time soon, it works and there are more pressing things to be done. By a quick test it seems that the develop branch still works with BS3 but of course I think there is no guarantee it won't break at some point.

 * Could the next version of the plugin support BS3 AND BS4?
 * Would you consider to create a new repository for a BS4 version so we can install and use both versions?
 * Any other solution?

_Copied from original issue: FriendsOfCake/search#213_

**Comment by ADmad** [comment]
_From @inoas on April 12, 2018 12:33_

Why do you want to integrate that anyway? Just override the templates or make them configurable and either have agnostic templates out of the box or BS4 onces (BS3 is now obsolete)?

**Comment by ADmad** [comment]
> Could the next version of the plugin support BS3 AND BS4?

If you mean having the same plugin version support BS3 and BS4, then the answer is "no", it would be a mess.

> Would you consider to create a new repository for a BS4 version so we can install and use both versions?

I personally am not interested in having the additional overhead of maintaining two separate repos.

> Any other solution?

You can probably fork the repo, and change the package name. Use foc/bui repo to install the BS3 version and use your own repo to install BS4 simultaneously. You probably won't even need to publish your fork to packagist since composer allows using git repos directly.

**Comment by burzum** [comment]
@ADmad thats what I had in mind but as last resort.

However, I've just tried to do that by renaming the namespace to Boostrap4Ui and updates composer.json and package.json in the Fork: https://github.com/World-Architects/bootstrap-ui/tree/bs4-namespace

I've tried to use it in our app by adding:

```json
"friendsofcake/bootstrap4-ui": "dev-bs4-namespace"
```

and

```json
	"repositories": [
		{
			"type": "vcs",
			"url": "git@github.com:World-Architects/bootstrap-ui.git"
		},
    ]
```

Resuling in:

```sh
λ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package friendsofcake/bootstrap4-ui could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by dereuromark** [comment]
We usually don't use "vcs", but "git" type:

      "type": "git",
      "url": "git@github.com:spryker/spryker.git"

This can yield better results when trying to work with Git(Hub) forks.

**Comment by burzum** [comment]
@dereuromark still the same issue.

**Comment by jorisvaesen** [comment]
I've created a repo which I will keep in sync with the future 1.x releases so we can use Bootstrap 3 and 4 in the same project: https://github.com/jorisvaesen/bootstrap-3-ui
