### ISSUE TITLE
protected _formAlignment to be public formAlignement

### ISSUE THREAD

**Issue by LubosRemplik** [FriendsOfCake/bootstrap-ui#229]
This is a 
* [x] enhancement

I think it would be good idea to make _formAlignment public method so it is possible to change alignement with element for example.

### What you did
Loading element via ajax with form fields but with no create / end form method.

### Expected Behavior
Alignement to be kept from template create (but it is not possible since we are loading just element via ajax request)

### Actual Behavior
Form with no alignement

**Comment by ADmad** [comment]
> Loading element via ajax with form fields but with no create / end form method.

How will the FormHelper get entity context if you don't use `create()`?  You can still use `create()/end()` for ajax calls just don't echo the method's result :slightly_smiling_face:.
