### ISSUE TITLE
BS4: select-box field with error does not have `is-invalid` class.

### ISSUE THREAD

**Issue by hdogan** [FriendsOfCake/bootstrap-ui#241]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: develop
* Bootstrap Framework Version: 4.1.3
* jQuery: 3.3.1 slim
* Platform and Target: Apache2, MySQL 5.7, PHP 7.2

### What you did
When form select-box control has an error, it does not have `is-invalid` class in select tag.

### Expected Behavior
`select` tag should have `is-invalid` class added when form control has an error.

### Actual Behavior
select-box input container (form-group) has `is-invalid` class added but `select` tag does not have it. Bootstrap does not render the error message container if the input does not have `is-invalid` class (it's `display` property is `none` by default - `is-invalid` class overwrites `display` property to `block`).

**Comment by ADmad** [comment]
I added a test which shows `is-invalid` class is applied to select tag https://github.com/FriendsOfCake/bootstrap-ui/commit/9d0b5174b77caf5eec5c9dbe9e1ba7504182f6e3#diff-cf0be6f0051f81c7f12aaa4c6becafc7R392

**Comment by hdogan** [comment]
Thanks for the test. I think I've got problem not related with the plugin but with core itself about handling habtm related inputs.
