### ISSUE TITLE
Element file "BootstrapUI.Element/Flash/default.ctp" is missing

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/bootstrap-ui#260]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 1.4.1
* Platform and Target: CakePHP 3.7

### What you did

    <?= $this->Flash->render() ?>

### Actual Behavior

> Element file "BootstrapUI.Element/Flash/default.ctp" is missing

The dot makes it look like CakePHP's plugin folder notation. 

- `APP/vendor/friendsofcake/bootstrap-ui/src/Template/Element/Flash/default.ctp` exists
- `APP/src/Template/Element/Flash/default.ctp` exists
- Also, I did try putting that file to `APP/src/Template/BootstrapUI.Element/Flash/default.ctp`, that didn't work

Unsure how to proceed. Are we not supposed to keep the Flash layouts together with the rest of the site anymore? Please clarify.

**Comment by ADmad** [comment]
The path `BootstrapUI.Element/Flash/default.ctp` should map to `vendor/friendsofcake/bootstrap-ui/src/Template/Element/Flash/default.ctp`. Not sure why Cake isn't able to find it. AFAIK there's no change regarding how element file paths are deduced in Cake 3.7.

**Comment by mehov** [comment]
Hi!

> Not sure why Cake isn't able to find it. 

Could it be something specific to my local configuration? What is it relying on that I should double check?

**Comment by mehov** [comment]
May be related: debug kit is not working either. I get *Error: DebugKitController could not be found* when requesting */debug-kit/toolbar/fada5a17-ee64-410c-a48d-96b57a5bf8a5*.

**Comment by ADmad** [comment]
Then you have messed up plugin loading somehow. Use one of Cake's help forum to figure out the cause.

**Comment by mehov** [comment]
> May be related: debug kit is not working either. I get _Error: DebugKitController could not be found_ when requesting _/debug-kit/toolbar/fada5a17-ee64-410c-a48d-96b57a5bf8a5_.

In case someone googles this, the problem was *RoutingMiddleware should be passed an application instance* (initially not shown), fixed by updating `Application.php` to match [the upstream version](https://github.com/cakephp/app/blob/master/src/Application.php#L61)

**Comment by acjbizar** [comment]
Just in case someone stumbles upon this; I had the same problem and it turned out I forgot to enable that plugin specifically:

```Shell
bin/cake plugin load BootstrapUI
```
