### ISSUE TITLE
FriendsOfCake/bootstrap-ui prefers it's own bundled `default.ctp` layout over the local one

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/bootstrap-ui#262]
This is a (multiple allowed):
* [x] bug
* [x] enhancement

* BootstrapUI Version: 1.4.1
* CakePHP Version: 3.7

### What you did
Installed FriendsOfCake/bootstrap-ui

### Expected Behavior
Seeing [`APP/src/Template/Layout/default.ctp`](https://github.com/cakephp/app/blob/master/src/Template/Layout/default.ctp)

### Actual Behavior
Seeing [`APP/vendor/friendsofcake/bootstrap-ui/src/Template/Layout/default.ctp`](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/Template/Layout/default.ctp)

### Workaround
`APP/vendor/friendsofcake/bootstrap-ui/src/Template/Layout/{default.ctp => default_del.ctp}`

### Details
Initially I had this exact issue when I first installed friendsofcake/bootstrap-ui long time ago. First thing I tried was seeing if [`setLayout()`](https://api.cakephp.org/3.7/class-Cake.View.ViewBuilder.html#_setLayout) or [`setLayoutPath()`](https://api.cakephp.org/3.7/class-Cake.View.ViewBuilder.html#_setLayoutPath) added to [`APP/src/View/AppView.php`](https://github.com/cakephp/app/blob/master/src/View/AppView.php) would help. 

- [`setLayoutPath()`](https://api.cakephp.org/3.7/class-Cake.View.ViewBuilder.html#_setLayoutPath) was restricted within just one folder, so didn't really make a difference. Trying something like `$this->setLayoutPath('../../../../../../src/Template/Layout')`, as ugly as it is, did not work. 
- [`setLayout()`](https://api.cakephp.org/3.7/class-Cake.View.ViewBuilder.html#_setLayout) worked, all I had to do was make sure my custom layout had a name different from `default.ctp`. 

There are a few problems with the latter approach:

- It is against [convention over configuration](https://book.cakephp.org/3.0/en/intro/conventions.html)
- I can no longer locally override with another layout. For example, `$this->viewBuilder()->setLayout('print');` inside a controller won't work: the site will continue using the layout configured inside `AppView.php`. However, disabling `setLayout()` returns to the expected layout (`print` in my example)

So the only acceptable workaround for me was making sure `APP/vendor/friendsofcake/bootstrap-ui/src/Template/Layout/default.ctp` isn't available. I renamed it (could've deleted as well). Seeing there's no vendor `default.ctp` layout file, the system reverted to the local `default.ctp` layout. This workaround required no further configuration, which means the system is pre-programmed to look for the default layout in it's default location, it just happens so that it prioritises the vendor location.

That worked for quite some time. Then I did an update, which restored the file, and led to confusion. I was wondering if a more elegant and permanent fix to this is planned.

**Comment by ADmad** [comment]
The layout file included in plugin is used by default but you can override it to use any layout from your app, for e.g. by using `$this->viewBuilder()->setLayout('default')` in your controller. The plugin's `default` layout can also be overridden without any code changes by creating file `APP/src/Template/Plugin/BootstrapUI/Layout/default.ctp` as per CakePHP's [convention](https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application).

*Never* modify files inside vendor directories. Your problems are borne out of inexperience with the framework, there's no actual issue. In future please use one of Cake's help forum's first.

**Comment by mehov** [comment]
> you can override it to use any layout from your app, for e.g. by using `$this->viewBuilder()->setLayout('default')` in your controller. 

First thing I tried, didn't help ([like I said above](https://github.com/FriendsOfCake/bootstrap-ui/issues/262#issue-397028804)).

> _Never_ modify files inside vendor directories. 

Deleting an interfering file seemed like a reasonable compromise at the time. I do know it's not the right way to handle this, hence me bringing this up.

> Your problems are borne out of inexperience with the framework

Sorry, I disagree about the whole framework. Sure, I'm not doing plugin development, so didn't know you can't optionally force the priority of app's default layout over plugin's. For those interested in reasoning behind it, [I found a relevant discussion in cakephp/cakephp](https://github.com/cakephp/cakephp/issues/4372).

> In future please use one of Cake's help forum's first.

I'm sorry if it looked like I'm abusing the issues here. Almost always I find answers on SO or in cake's core myself. If I post here, it's for people searching through issues or googlers, and I close issues myself when I have all the information - unless you manage to close it before I do. 

I left this issue opened because I needed actual developers' perspective.

> The plugin's `default` layout can also be overridden without any code changes by creating file `APP/src/Template/Plugin/BootstrapUI/Layout/default.ctp` as per CakePHP's [convention](https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application).

Moving/duplicating my default layout outside its expected location into a plugin that it doesn't depend on isn't a clean solution. However, this brought me to the idea of adding a relative symlink, which worked. Thanks for the tip!

### TD; DR: the optimal solution

    ln -s ../../../Layout/default.ctp /var/www/app/src/Template/Plugin/BootstrapUI/Layout/default.ctp

This will create a shortcut pointing to your default layout in its original location, without duplicating or moving the actual file. BootstrapUI will detect the shortcut and reuse the target layout instead of the one bundled with the plugin.

**Comment by groovenectar** [comment]
@mehov I'm running into this as well

Interesting solution with the symlink to avoid the unexpected path, may have to go that route

I wonder if the plugin uses a different name than `default.ctp` if the issue would be avoided, and the helper classes would be applied without the unexpected layout update... Then we could reference the plugin's layout files as-needed, or just migrate some of the contents into the app layouts

**Comment by davidspeijer** [comment]
With the [documentation for CakePHP4](https://book.cakephp.org/4/en/plugins.html#overriding-plugin-templates-from-inside-your-application) the suggested path to overwrite is `templates/plugin/TheVendor/ThePlugin/Custom/index.php`. So I added templates `/plugin/friendsofcake/bootstrap-ui/layout/default.php`. however the overwrite file is not used. any suggestions?
