### ISSUE TITLE
Checkbox HTML does not match the readme

### ISSUE THREAD

**Issue by bigasbespip** [FriendsOfCake/bootstrap-ui#265]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: dev-develop.

### What you did
Installed cake and this plugin via CLI:
composer create-project --prefer-dist cakephp/app boottest
boottest/
composer require friendsofcake/bootstrap-ui:dev-develop
cake plugin load BootstrapUI
cake bootstrap install
cake bootstrap modify_view
cake bootstrap copy_layouts

Modified home.ctp:

<?php
        echo $this->Form->create();
        echo $this->Form->control('title');
        echo $this->Form->control('published', ['type' => 'checkbox']);
?>

### Expected Behavior
Expected to see identical output as the readme:
*SNIP*
```html
  <div class="form-check">
    <input type="hidden" name="published" value="0">
    <label for="published">
      <input type="checkbox" name="published" value="1" id="published">Published
    </label>
  </div>
```
*SNIP*

### Actual Behavior
Got this output:
*SNIP*
```html
<div class="form-group form-check checkbox">
<input type="hidden" name="published" value="0">
<input type="checkbox" name="published" value="1" id="published" class="form-check-input">
<label class="form-check-label" for="published">Published</label>
</div>
```
*SNIP*

**Comment by dereuromark** [comment]
Use ```php for code fencing.

Use ``` for closing it.

**Comment by bigasbespip** [comment]
@dereuromark cheers, missed it first time.

**Comment by ADmad** [comment]
PR to update the README for `develop` branch in welcome. Boostrap 4 doesn't nest radio/check inside label anymore.

**Comment by dereuromark** [comment]
@bigasbespip Are you interested in making a PR to fix up the docs?
