### ISSUE TITLE
Inline labels are screen reader only, so they do not display

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/bootstrap-ui#277]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: d61733535cad6f4ec1c966bacc6cafaef3f461c0
* Bootstrap Framework Version: 3.3.7
* jQuery: 2.1.4
* Platform and Target: Nginx, PHP

### What you did
I created an inline form for my search.
```php
    echo $this->Form->create(null, ['class' => 'form-inline pull-left', 'valueSources' => 'query']);
    echo $this->Form->control('name');
    echo $this->Form->control('provider_type', ['empty' => 'Any type']);
    echo $this->Form->control('visibility', ['empty' => 'Any visibility', 'options' => [0 => 'Paused', 1 => 'Live']]);
    echo $this->Form->button('<span class=\'glyphicon glyphicon-search\'></span> Filter',['type' => 'submit', 'class' => 'btn btn-success']);
    echo $this->Html->link('Reset', ['action' => 'index', '?' => ['preserve' => 0]], ['class' => 'btn btn-default']);
    echo $this->Form->end();
```

### Expected Behavior
Previous version the label was being displayed.

### Actual Behavior
The label now has a class of `sr-only` which hides the labels, making my form inputs look confusing because users don't know what the field is.

### Documentation
Always add labels
Screen readers will have trouble with your forms if you don't include a label for every input. For these inline forms, you can hide the labels using the .sr-only class. There are further alternative methods of providing a label for assistive technologies, such as the aria-label, aria-labelledby or title attribute. If none of these is present, screen readers may resort to using the placeholder attribute, if present, but note that use of placeholder as a replacement for other labelling methods is not advised.

**Comment by ADmad** [comment]
> Previous version the label was being displayed.

What previous version are you referring to?  The commit you have linked just makes changes to avoid deprecation errors. I don't remember any change in recent times which add `sr-only` class to labels.

Can you show the generated HTML?

**Comment by ADmad** [comment]
The `sr-only` class for labels when using inline form exists since `1.0.0` release of the plugin.

https://github.com/FriendsOfCake/bootstrap-ui/blob/46840ae2cf829f91a2b1ddb52c968fe4cdd3bef0/src/View/Helper/FormHelper.php#L59

**Comment by ADmad** [comment]
Bootstrap [docs](https://getbootstrap.com/docs/3.4/css/#forms-inline) show use of `sr-only` on labels for inline forms, so I guess that's what was implemented.

If you don't want the `sr-only` class just override the template.

**Comment by davidyell** [comment]
To be fair the docs you linked to show both. I've overridden the templates now, I'll just have to remember to include this every time 😄

**Comment by ADmad** [comment]
The more important fact is this behavior has existed since `1.0.0` :slightly_smiling_face:.
