### ISSUE TITLE
type radio broken

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#29]
```php
echo $this->Form->input('gender', ['type' => 'radio', 'options' => ['Male', 'Female']]);
```

![unbenannt](https://cloud.githubusercontent.com/assets/39854/6882362/399a56ce-d582-11e4-981b-d491ef319965.PNG)

The radio button appears twice per value

**Comment by jadb** [comment]
I think this is resolved in the current 0.3 (dev). Keeping it open for now as it might need fixing on 0.2 if there are BC in 0.3 (for people who will stick to 0.2 for now).
