### ISSUE TITLE
.fade makes alerts not visible

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/bootstrap-ui#291]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 1.4.1
* Bootstrap Framework Version: 4.0.0
* jQuery: 3.3.1

### What you did
````
$this->Flash->success(__('test 1'));
$this->Flash->error(__('test 2'));
````
### Expected Behavior
Both alerts rendered and visible.

### Actual Behavior
Both alerts rendered but invisible because `.fade` has `opacity: 0;` and `.in` doesn't kick in for some reason. If I remove the `.fade` class, both alerts are immediately visible.

As far as I can see, `.fade.in` [was added all the way back in 2015](https://github.com/FriendsOfCake/bootstrap-ui/commit/84ecbbb4d96161223895aa51657c639c48548ce1#diff-ce433546a945ec9335df4c40c648c3c9R23). I found [this answer from 2018](https://stackoverflow.com/questions/48594068/bootstrap-4-default-tab-pane-active-fade-in-not-working) saying things have changed in Bootstrap v4; it covers the tabs, but it could be the same for the alerts.

Are those two CSS classes needed? Or would removing both `.fade` and `.in` from [`_defaultConfig`](https://github.com/FriendsOfCake/bootstrap-ui/blob/8e476595fb594f5de81428ac71362c67683ea958/src/View/Helper/FlashHelper.php#L24) solve this?

**Comment by ADmad** [comment]
`1.x` version of the plugin is only meant for Bootstrap 3, not 4. Use the `2.x` beta releases if you want to use with Bootstrap 4.
