### ISSUE TITLE
Overwrite default.php BS4 CakePHP 4

### ISSUE THREAD

**Issue by davidspeijer** [FriendsOfCake/bootstrap-ui#298]
The layout file included in plugin is used by default but you can override it to use any layout from your app, for e.g. by using `$this->viewBuilder()->setLayout('default')` in your controller. The plugin's `default` layout can also be overridden without any code changes by creating file `APP/src/Template/Plugin/BootstrapUI/Layout/default.ctp` as per CakePHP's [convention](https://book.cakephp.org/3.0/en/plugins.html#overriding-plugin-templates-from-inside-your-application).

*Never* modify files inside vendor directories. Your problems are borne out of inexperience with the framework, there's no actual issue. In future please use one of Cake's help forum's first.

_Originally posted by @ADmad in https://github.com/FriendsOfCake/bootstrap-ui/issues/262#issuecomment-452549581_

With the [documentation for CakePHP4](https://book.cakephp.org/4/en/plugins.html#overriding-plugin-templates-from-inside-your-application) the suggested path to overwrite is `templates/plugin/TheVendor/ThePlugin/Custom/index.php`. So I added templates `/plugin/friendsofcake/bootstrap-ui/layout/default.php`. however the overwrite file is not used. any suggestions?

**Comment by ADmad** [comment]
> So I added templates /plugin/friendsofcake/bootstrap-ui/layout/default.php

Casing matters, the path should be `/templates/plugin/FriendsOfCake/BootstrapUI/layout/default.php`.
