### ISSUE TITLE
Instruction to install cake-4-bs-4

### ISSUE THREAD

**Issue by vnt** [FriendsOfCake/bootstrap-ui#312]
Hi,
I want to try cake-4-bs-4,
Where can I find the instructions to install and configure cake-4-bs-4?

**Comment by cewi** [comment]
For me
`composer require friendsofcake/bootstrap-ui:^3.0`
worked for installation

**Comment by vnt** [comment]
No it doesn't work for me

Composer require friendsofcake/bootstrap-ui:^3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package friendsofcake/bootstrap-ui ^3.0 is satisfiable by friendsofcake/bootstrap-ui[3.0.0-beta, 3.0.0-beta2, 3.0.0-beta3, 3.0.0-beta4] but these conflict with your requirements or minimum-stability.

**Comment by ADmad** [comment]
Either use version as `^3.0@beta` or set `minimum-stability` to `beta` in your composer config.
