### ISSUE TITLE
Datetime as input vs select

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#32]
https://github.com/FriendsOfCake/bootstrap-ui/pull/31 makes the default date(time) work in Cake just fine.

But in general, we should have the option to switch to a text field with datepicker support, e.g. using http://eonasdan.github.io/bootstrap-datetimepicker/
This could be done using a custom datetime widget, I guess, which then just requires the necessary JS files to be included (manually) to work.
Settings for localization and stuff will need to be optionized somehow, though.

**Comment by davidyell** [comment]
Aren't date pickers part of HTML5 now?

**Comment by ADmad** [comment]
They are but pretty sure they are still not consistently implemented across all browsers. Plus sadly often once needs to support older versions of IE.

**Comment by jadb** [comment]
Yes, but you'd still need to offer a fallback for the ones that are still using old browsers.

I personally don't like the multiple `<SELECT>` for dates but that's what comes with cake and the plugin is supposed to 'transparently' wrap cake.

**Comment by matrich** [comment]
@dereuromark , has this feature been implemented so that a datetime picker can be used? or where can i find help on how to have it work?

**Comment by ADmad** [comment]
To use a js datetime widget all one needs to do is set field type to `text` and attach the js to that input. No direct js dependencies will be added to this plugin.

**Comment by dereuromark** [comment]
The ticket is about the not merged PR which contains some minor fixes that are related to it.
And some fixing this issue needs in general.
I agree that JS dependencies should be app not plugin specific.

**Comment by ADmad** [comment]
@dereuromark Does the issue exist in current master branch? If this ticket can be closed?

**Comment by dereuromark** [comment]
I don't think my improvements have been merged. So there is still some limitation existent yet.

**Comment by dereuromark** [comment]
Can someone please pull in the fixes from https://github.com/FriendsOfCake/bootstrap-ui/pull/31 ?
The datetime default dropdowns still look like crap, and it would be quite easy to at least have a basic support here.
Thanks guys.

**Comment by lorenzo** [comment]
@dereuromark It would probably be easier if you open a new pull request with the changes

**Comment by ayman-alkom** [comment]
I have an idea 
I noticed that this plugin doesn't have any configuration 
I think that features like date pickers can be switched by the configuration to serve the users who like to support the old browser.
we can make two PR, one for enhance the look of date combo-boxes, and one for whose want to use the date pickers.

**Comment by ayman-alkom** [comment]
Hi @dereuromark, you can look at this PR
 https://github.com/FriendsOfCake/bootstrap-ui/pull/80

**Comment by dereuromark** [comment]
The custom CSS styling of my PR 31 could be useful and implemented, other than that we can close this.

**Comment by jadb** [comment]
@dereuromark #31 wasn't finished, required more work. Have time for it?

**Comment by dereuromark** [comment]
Not at this point I am afraid.

**Comment by davidyell** [comment]
To add something I found today, the helpers don't 'Bootstrapify' `Form->month()` or `Form->year()` dropdowns.
