### ISSUE TITLE
Pagination default template broken

### ISSUE THREAD

**Issue by reloxx13** [FriendsOfCake/bootstrap-ui#323]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

Heya,

im using the latest master version, and the pagination has lost its bootstrap classes like page-link etc.

Is this supposed?

I canot find a commit removing them.

Bootstrap docs: https://getbootstrap.com/docs/4.5/components/pagination/#overview

From master (newer) without bootstrap classes:
https://github.com/FriendsOfCake/bootstrap-ui/blob/f0cf8917b6cd778200f928ab6d3bb52a2a099328/src/View/Helper/PaginatorHelper.php#L29-L37

From dev (older) with bootstrap classes:
https://github.com/FriendsOfCake/bootstrap-ui/blob/98a874bbeb4ab9c5a11fb91ae3260d77fda91217/src/View/Helper/PaginatorHelper.php#L18-L29

**Comment by dereuromark** [comment]
Is this still an issue?
For me and the paginator it seems to work fine
https://sandbox.dereuromark.de/sandbox/search-examples/table
Are you sure it doesn't load the normal "app" level helper instead?

**Comment by reloxx13** [comment]
It should not, ill check the next time i add a pagination.
