### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#330]
Can we release also beta of v2?

cake4 + bs3 if I understand correctly
that would ease the migration of cake 3 to 4 if you don't also have to replace all templates right away.

**Comment by ADmad** [comment]
The v2 branch (`develop`) is usable but not sure if I would consider it stable. That said I don't use myself and don't have much motivation to review it and see if needs improvements. So I am happy to tag is stable if that's what people want.

**Comment by dereuromark** [comment]
We could tag the beta for now, and just see if more people contribute over time to stabilize
Since we have now v3 anyway released, there is nothing preventing us from leveraging also v2 release major. :)

**Comment by ADmad** [comment]
> cake4 + bs3 if I understand correctly

Ummm nope. `2.x` is Cake 3 and BS 4. We don't have any branch for Cake 4 and BS 3.

**Comment by dereuromark** [comment]
Yes, my bad. The missing combination would be release `v4 1/3` ;)

So, yeah: bs4 and cake3 was what I meant.

**Comment by ADmad** [comment]
I released `2.0.0-RC`. Will do a stable release in couple of weeks (or whenever someone gives a reminder if i forget :slightly_smiling_face:).
