### ISSUE TITLE
Add class to inputContainer

### ISSUE THREAD

**Issue by davidspeijer** [FriendsOfCake/bootstrap-ui#335]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 3.0.1
* Bootstrap Framework Version: 4.3.1
* jQuery: 3.5.1
* Platform and Target: 

### What you did
```
<?= $this->Form->control('firstname',
	[
		'placeholder' => __('Enter your first name'),
		'inputContainer' => ['class'=>'col-md-6'],
		'label'=>[
			'text'=>__('First name'),
			'class'=>'small mb-1']
	]) ?>
```

### Expected Behavior
Have the col-md-6 class added to the inputContainer
```
<div class="form-group **col-md-6** text">
	<label class="small mb-1" for="firstname">First name</label>
	<input type="text" name="firstname" placeholder="Enter your first name" inputcontainer="test" id="firstname" class="form-control" value="David" maxlength="50">
</div>
```

### Actual Behavior
inputContainer is not having the class added
```
<div class="form-group text">
	<label class="small mb-1" for="firstname">First name</label>
	<input type="text" name="firstname" placeholder="Enter your first name" inputcontainer="test" id="firstname" class="form-control" value="David" maxlength="50">
</div>
```

**Comment by dereuromark** [comment]
A PR with the suggested fix would be very welcome.

**Comment by davidspeijer** [comment]
To be honest; I have no clue how to fix :-).

**Comment by ndm2** [comment]
Not really a bug, or is it? AFAICT there's just no support for it, the core form helper doesn't support custom container attributes via options either.

I'm wondering, @davidspeijer is there a reason that [**horizontal forms**](https://github.com/FriendsOfCake/bootstrap-ui/tree/3.0.1#horizontal-forms) don't do it for you?

Generally being able to set custom container attributes could be relatively useful, it would help to avoid having to supply custom templates for simple changes, but the overly stuffed templates already aren't overly appreciated, and this would require adding at least two additional template variables to all the container templates, one for the class, as the class attribute already exists in the templates, and one for additional attributes.

Example, templates like these:

```html
<div class="form-group {{type}}{{required}}">{{content}}{{help}}</div>
<div class="form-group {{formGroupPosition}}{{type}}{{required}} is-invalid">{{content}}{{error}}{{help}}</div>
```

would need to become something like this:

```html
<div{{containerAttrs}} class="form-group {{containerClass}}{{type}}{{required}}">{{content}}{{help}}</div>
<div{{containerAttrs}} class="form-group {{containerClass}}{{formGroupPosition}}{{type}}{{required}} is-invalid">{{content}}{{error}}{{help}}</div>
```

**Comment by davidspeijer** [comment]
@ndm2 I'm implementing the startbootstrap.com admin pro template (https://sb-admin-pro.startbootstrap.com/account-profile.html) in my project where they use the fields in that way.

By adding a <div class="col-md-5"> around the field it "solves" the problem. However adding a class to the form-group div would be cleaner.

```
<!-- Form Row-->
<div class="form-row">
    <!-- Form Group (first name)-->
    <div class="col-md-5">
        <?= $this->Form->control('firstname',['placeholder'=>__('Enter your first name'),'inputContainer'=>['label'=>['text'=>__('First name'),'class'=>'small mb-1']]) ?>
    </div>
    <!-- Form Group (middle name)-->
    <div class="col-md-2">
        <?= $this->Form->control('middlename',['placeholder'=>__('Enter your middle name'),'inputContainer'=>['label'=>['text'=>__('Middle name'),'class'=>'small mb-1']]) ?>
    </div>
    <!-- Form Group (last name)-->
    <div class="col-md-5">
        <?= $this->Form->control('lastname',['placeholder'=>__('Enter your middle name'),'inputContainer'=>['label'=>['text'=>__('Last name'),'class'=>'small mb-1']]) ?>
    </div>
</div>
```

**Comment by ndm2** [comment]
I see, wrapping the controls seems easy enough. However, I can take a look at it in case there's interest in the feature, and no objections to more complex templates.

**Comment by davidspeijer** [comment]
I would appreciate it if you tried to get this feature going! I have no objection to more complex templates ;-)
