### ISSUE TITLE
Paginator limit control is missing form-label class

### ISSUE THREAD

**Issue by gunner1095** [FriendsOfCake/bootstrap-ui#339]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 3.0.3
* Bootstrap Framework Version: 4
* Platform and Target: WAMP

### What you did
Used PaginatorHelper to generate a limit control.

```php
$this->Paginator->limitControl(); 
```

### Expected Behavior
Expected a properly formatted limit control like this:
```html
<div class="form-group select">
  <label class="form-label" for="limit">Limit</label>
  <select name="limit" class="form-control" onchange="this.form.submit()" id="limit">
    <option value="20" selected="selected">20</option>
    <option value="50">50</option>
    <option value="100">100</option>
  </select>
</div>
```

### Actual Behavior
The helper did not add the 'form-label' class to the label.
```html
<div class="form-group select">
  <label for="limit">Limit</label>
  <select name="limit" class="form-control" onchange="this.form.submit()" id="limit">
    <option value="20" selected="selected">20</option>
    <option value="50">50</option>
    <option value="100">100</option>
  </select>
</div>
```

I think this can be fixed by adding something like this to the PaginatorHelper class:
```php
    public function limitControl(array $limits = [], ?int $default = null, array $options = []): string
    {
        // Inject form-label class into the label by default
        return parent::limitControl($limits, $default, $options += ['label' => ['class' => 'form-label']]);
    }
```

**Comment by ndm2** [comment]
That is the expected behavior, there is no `form-label` class in Bootstrap 4.x, that's a new class that is going to be introduced with Bootstrap 5.x.

**Comment by gunner1095** [comment]
You're right. I was comparing it to the wrong example. Sorry about that!
