### ISSUE TITLE
Alert doesn't have linebreak

### ISSUE THREAD

**Issue by koraykupe** [FriendsOfCake/bootstrap-ui#342]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 3.0.1
* Bootstrap Framework Version: 4.3.1
* jQuery: 3.5.0
* Platform and Target: - (localhost)

### What you did
Added UIViewTrait to the AppView. Extended the signin layout in a login view, and created a form in it.

### Expected Behavior
Alert should have linebreak

### Actual Behavior
Alert is shown like that:
<img width="673" alt="Screenshot 2021-01-26 at 11 48 11" src="https://user-images.githubusercontent.com/5278340/105835673-23ebd000-5fdd-11eb-9b63-575f65bf998f.png">

**Comment by ndm2** [comment]
This is caused by the wrong flex layout direction being applied.

This pull request should fix it: https://github.com/FriendsOfCake/bootstrap-ui/pull/344. If you can, please give it a try in your app (make sure that you clear the browser cache).
