### ISSUE TITLE
bake using "-t BootstrapUI" throws error

### ISSUE THREAD

**Issue by ThoWen77** [FriendsOfCake/bootstrap-ui#343]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: 3.0.1
* Bootstrap Framework Version: v4.3.1 (i guess)
* jQuery: v3.5.0 (i guess)
* Platform and Target: Xubuntu 18.04, CakePHP 4.0.4

### What you did
bin/cake bake all ExampleModels -t BootstrapUI

table name: example_models

### Expected Behavior
Well, the baked skeleton for this table with the bootstrap-UI attached

### Actual Behavior
all started good, the index and the view templates looks fine, but then...

Baking `view` view template file...

Creating file /var/www/myproject/templates/ExampleModels/view.php
Wrote `/var/www/myproject/templates/ExampleModels/view.php`
Exception: Unknown "element" function.
In [/var/www/myproject/vendor/friendsofcake/bootstrap-ui/templates/bake/Template/add.twig, line 15]

2021-02-01 11:46:28 Error: [Twig\Error\SyntaxError] Unknown "element" function. in /var/www/myproject/vendor/friendsofcake/bootstrap-ui/templates/bake/Template/add.twig on line 15

**Comment by ndm2** [comment]
It's working fine for me, can anyone else reproduce this?

**Comment by ThoWen77** [comment]
I needed to update CakePHP (to 4.2.3) with "composer update".
After that update the bake worked as expected.

Maybe the bootstrap-ui verson was somehow incompatible with the previous CakePHP version.

I noticed the update removed in vendor/cakephp-plugins

`'WyriHaximus/TwigView' => $baseDir . '/vendor/wyrihaximus/twig-view/'`

and added

`'Cake/TwigView' => $baseDir . '/vendor/cakephp/twig-view/',`

**Comment by ndm2** [comment]
> EDIT: If the versions are not compatible, shouldn't composer don't install this version of bootstrap-ui in first place?

Composer isn't that smart :) The twig view plugin is a dependency of `cakephp/bake`, and BootstrapUI doesn't require neither of them itself.

Maybe you've updated earlier at an unfortunate time, where bake was still using the old twig view plugin, and BootstrapUI already relied on the newer one.

**Comment by ThoWen77** [comment]
OK, thanks
