### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by calcosta** [FriendsOfCake/bootstrap-ui#347]
This is a (multiple allowed):
* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

Is there a roadmap for Bootstrap 5 support?
Bootstrap 5 is currently in Beta2 and seems to be pretty decent. The complete drop of jQuery makes it more flexible.

**Comment by ADmad** [comment]
> Is there a roadmap for Bootstrap 5 support?

That road hasn't been planned yet :slightly_smiling_face:. It can be greatly accelerated if someone submits a pull request for the same.

**Comment by calcosta** [comment]
Ok, I'll check if I can help :)

**Comment by ndm2** [comment]
So Bootstrap 5 is out now... I'll take a look into it when I have a little more free time in the next few weeks, and see what would need to be done, but I'm pretty sure that it's not possible to support both 4.x and 5.x simultaneously, ie we'd most likely need a new major and maintain them separately.

**Comment by ADmad** [comment]
> we'd most likely need a new major and maintain them separately.

Yup

**Comment by ndm2** [comment]
I've opened [a new issue](#349) that tracks problems and tasks.

**Comment by dereuromark** [comment]
Closing in favor of linked ticket
