### ISSUE TITLE
Bootstrap 5 Support - Tasks and problems

### ISSUE THREAD

**Issue by ndm2** [FriendsOfCake/bootstrap-ui#349]
It seems that overall, supporting BS5 will not require too drastic changes, there's a few things broken, but it's absolutely nothing like the BS3 to BS4 transition, most of the generated HTML seems compatible as-is.

Here's a most likely incomplete list of problems/tasks that I've found so far (some of them might also be problems in the current version, which can be backported later on).

General
---

* [x] Upgrade dependencies (drop jQuery, upgrade Popper to 2.x).
* [x] Screenreader-only content is not being hidden (`sr-only` has been renamed to `visually-hidden`).
* [x] Update custom CSS according to browser support changes (prefixes no longer required, etc).
* [x] Update documentation.

Form Helper
---

* [x] Labels are missing bottom margins (they now require a `form-label` class).
* [x] Controls are missing bottom margins (`.form-group` has been removed).
* [x] Inline multi checkbox groups are not inline aligned (`.form-inline` has been removed).
* [x] Remove custom controls, the "custom" style is now the default.
* [x] File input not rendering correctly (`.form-control-file` has been removed).
* [x] Range control labels are vertically misaligned in horizontal forms.
* [x] Select controls should use `form-select` instead of `form-control`.
* [x] Input group addons no longer use a wrapper (`.input-group-append` and `.input-group-prepend` have been removed).
* [x] Tooltips do not toggle anymore (`data-toggle` has been renamed to `data-bs-toggle`).
* [x] Combined inline controls collapse into each other (`.form-inline` has been removed).
* [x] Checkbox help text sticks to the right side of the label (`.form-text` does not set block level display anymore).
* [x] Use rows and columns for [inline forms](https://getbootstrap.com/docs/5.0/forms/layout/#inline-forms).
* [x] ~Custom input classes for radio and checkbox controls prevent `is-invalid` from being added (problem is in core radio widget, it merges options using `+`).~ Not worth the hassle right now.
* [x] Check if and where `pt` classes are still needed... they _are_ needed for range, radio and multi checkbox.
* [x] ~Remove no longer available `form-group` and `form-inline`?~ Keeping them should do no harm, in fact, they make it easier for people to apply their own styles.
* [x] ~Remove seemingly no longer needed `d-block` classes for labels?~ Actually still required.
* [x] Remove backwards compatibility tests?
* [x] Add support for [help text](https://getbootstrap.com/docs/5.0/forms/overview/#form-text) association using `aria-describedby`?
* [x] Add support for multiple ID reference lists for `aria-describedby`, and include references to error messages additionally to help text.
* [x] Add support for [floating labels](https://getbootstrap.com/docs/5.0/forms/floating-labels/)? They are a bit tricky, in horizontal forms, labels would need to be grouped with the control in the right column, and for inline forms the label would need to be not hidden.
* [x] Add support for [multiple input group text addons](https://getbootstrap.com/docs/5.0/forms/input-group/#multiple-addons)?
* [x] Add [color control](https://getbootstrap.com/docs/5.0/forms/form-control/#color)?
* [x] ~Add [datalist](https://getbootstrap.com/docs/5.0/forms/form-control/#datalists) support?~ Not yet.
* [x] Add [switch](https://getbootstrap.com/docs/5.0/forms/checks-radios/#switches) support?
* [x] ~Add support for [toggles](https://getbootstrap.com/docs/5.0/forms/checks-radios/#toggle-buttons)?~ Nah...

Html Helper
---

* [x] Badges have no background.
* [x] Remove deprecated `label()` method.

Flash Helper
---

* [x] Flash messages cannot be dismissed (`data-dismiss` has been renamed to `data-bs-dismiss`).
* [x] Flash message close icon is not rendering correctly.
* [x] Add support for (custom) icons via options?

Icons
---

* [x] Drop Font Awesome, use and include [Bootstrap Icons](https://icons.getbootstrap.com) by default instead?

Bake templates / Template styles
---

* [x] `dashboard.ctp` navbar is rendering the brand incorrectly.
* [x] `dashboard.ctp` sidebar layout is broken.
* [x] `view.ctp` renders text column types incorrectly.
* [x] `login.ctp` is missing margins.
* [x] `login.ctp` should render Flash messages and form inside of the same container?

---

I've already done/fixed some things, because why not, I was already on it, so I could as well just do it. I'll push an open PR shortly.

However I've only taken care of actual necessities so far, as other problems/tasks require some feedback, specifically the ones that have a question mark. If anyone has any input on this, it would be very much appreciated!

**Comment by ndm2** [comment]
In case there will be no objections, I will add support for color and switches, in the hope that [this color validation bug](https://github.com/twbs/bootstrap/issues/34151) will be fixed sometime soon.

I'm not a fan of radio toggle buttons, it feels like a really bad UX to me personally, so I'm probably not gonna bother with them. Datalists, I'm not sure, but given their inconsistent behavior between browsers, I'm not overly intrigued putting work into this right now.

**Comment by ndm2** [comment]
Any opinions on dropping the `middle` align key, and using `left` and `right` only? AFAICT `right` was introduced and dropped in one and the same PR back in the days, and somehow carried over all those years.

It always looks weird to me referring to the "middle" position when there's only two columns. Not sure why it's still there... for people that extend the plugin maybe?

An alternative could possibly be to not use names, and just use a numerically indexed array, where the index is the column number, eg:

```php
'align' => [
    'sm' => [
        4, // first column
        8, // second column
    ],
]
```

**Comment by ndm2** [comment]
I'll take the silence as consent to do with it whatever I'd like to do :shipit:

**Comment by ADmad** [comment]
> I'll take the silence as consent to do with it whatever I'd like to do :shipit:

Yes please 🙂.

**Comment by ndm2** [comment]
Well... I kinda like this, where the constants hold integers, `0` and `1` respectively here (which still allows for a basic numerically indexed arrays to be passed).

```php
'align' => [
    'sm' => [
        FormHelper::GRID_COLUMN_ONE => 6,
        FormHelper::GRID_COLUMN_TWO => 6,
    ],
    'md' => [
        FormHelper::GRID_COLUMN_ONE => 4,
        FormHelper::GRID_COLUMN_TWO => 8,
    ],
],
```

This makes no assumptions about how many columns there can possibly be, people could extend the helper (with up to twelve columns) without having to come up with weird names to fit the scheme, like, I don't know, `moreRight`, `evenMoreToTheRightThanBefore`, `moreToTheRightAgainButNoYetQuiteFullyToTheRightThereIsMoreToCome`...

I'll have to think about it for a minute or two.

**Comment by umer936** [comment]
Bootstrap 5.1 released the other month. 

Doesn't look like anything that breaks any tasks on here - mostly some new stuff. 

Releaselog can be found here: https://github.com/twbs/bootstrap/releases/tag/v5.1.0

**Comment by ndm2** [comment]
Looks like it should be fine, yeah. The color control shrinking bug fix is included, that's nice. I'll look into it later when I've finished the ARIA attribute stuff, this needs some additional care so that it works with the new ARIA attributes introduced with the upcoming CakePHP 4.3, and doesn't blow up the testsuite.

**Comment by ndm2** [comment]
I'm done for now, my list is complete. I'll tag another RC, and if no further major changes are being introduced, I'd personally be fine with a stable release after that.

If anyone has any additional wishes, suggestions, complaints, whatever, please voice them.

**Comment by gerhard-lechner** [comment]
Thanks for the great update, @ndm2 ! However, I realised that there are quite a few classes hardcoded in the helpers now, most notably the `mb-3` class in `_containerOptions()`. I guess that this particular class isn't desirable in all use cases, even if it is used throughout the bootstrap documentation examples.

Of course I can change this to -for example- `mb-2` by doing `$this->Form->control('foo', ['container' => ['class' => 'mb-2', 'skip' => 'mb-3']]`, but that is cumbersome as you might agree. Why not assign the default values to `$_defaultConfig` and hence make it configurable upon initialisation of the helper through the `$config` array? Ideally also considering `null` values (i.e. not add any class), as one might just apply the desired spacing to the `.form-group` class.

The same also applies to a few other cases like

- `ps-4` in `_labelOptions`
- `d-block` in `_helpOptions`
- `g-3` in `_formAlignment`

and probably similar patterns in other helpers.

I think this additional flexibility would help everyone who is using a customised version of bootstrap and wants to customise the UI to more specific needs. What do you think?

**Comment by gerhard-lechner** [comment]
I understand that `mb-3` is a good starting point for the default scenario. However, I think there's an important difference between

- classes that are *needed* to get an expected result (e.g. the `form-floating` class in the `_containerOptions()` method) and
- classes that are just *nice-to-have* (i.e. purely for styling, like the `mb-3` in the same method).

In the first example at https://getbootstrap.com/docs/5.1/forms/floating-labels/ the first input has the `mb-3` class whereas the second input doesn't have it. So clearly it depends on the situation. Maybe I want it to be `mb-6` in another case to create some extra spacing between inputs.

In my opinion it's always better to apply only the classes i *actually* want than having to remove some defaults I've never set and can't even change. Therefore I'd definitely prefer being able to influence these nice-to-have default classes (or in my case even set them to `null` to just get rid of them) as my personal take would be that the bootstrap-ui helpers should focus only on classes that are actually *needed*.

Of course I can always create a wrapper method that sets `['container' => ['skip' => 'mb-3']]` but I thought there's no harm in just making it configurable instead of having styling classes hard-coded?

**Comment by gerhard-lechner** [comment]
The solution for icons in HtmlHelper is by the way a very good example (even if not 100 % the same). However, if I don't use the bootstrap icons but for example FontAwesome, I can just set

```
$config['iconDefaults'] = ['namespace' => 'fas', 'prefix' => 'fa'];
```

et voilà - issue solved. I think a somewhat equal approach would be great for the nice-to-have classes mentioned too.

**Comment by ndm2** [comment]
I'm not sure, I think I'd argue that the icon helper is very different, as the classes here are tied to its main functionality. The classes in the form helper on the other hand are either of "optional"/"decorative", or workaround nature.

I'm inclined to agree as far as pure styling classes go that are just "a matter of tase", like `mb-3` and `g-3`, as they just define spacing (which isn't there anymore by default for `form-group` since BS5). `d-block` on the other hand would be an example of something that is very much required, it's a workaround to make errors and help text show up in situations where Bootstrap's sibling based selector for those elements unfortunately doesn't match. And the `pt-` classes, without them the alignment of labels is off, it's something that's used in the BS docs examples too, so I'm not sure in which category I'd put them 🤔 And lastly there's `ms-0` for the error element, this also is alignment related.

I'd say the container and inline grid spacing would be something where configuration might be considered reasonable, but I'd like to hear 1 or 2 more opinions on this. Ideally, if such options were added, they would be somewhat, well, not neccesarily "version idependent", but somewhat "generic" enough to not be directly associated with specific Bootstrap features, if that makes any sense.

**Comment by gerhard-lechner** [comment]
After digging a bit more into BS5, I still think the `mb-3` shouldn't be added automatically by the helper. All of the somewhat advanced examples actually use `g-3`, e.g. the second example at https://getbootstrap.com/docs/5.1/forms/overview/#form-text ... so why not leave that decision to the programmer? I think the helper shouldn't be concerned about creating a perfectly styled **form** but only about creating an **input field**.

However, I wanted to add another suggestion regarding the floating labels: These actually only work as expected if a placeholder is set. So in my wrapper class that extends the bootstrap-ui FormHelper I added something like this:

```
if ($options['labe']['floating'] === true and !isset($options['placeholder'])) {
    $options['placeholder'] = $options['label']['text'];
}
```

Do you think that would make sense as part of the bootstrap-ui helper or is it up to the developer to manually define a placeholder?

**Comment by ndm2** [comment]
The gutter classes are for inline forms, and that's what the helper will use for them accordingly. Vertical forms use the bottom margin classes. No further input has been provided, so I'll open a PR with a suggestion how the gutter/margin class could be made configurable, and we'll see if there are any objections.

As far as the floating labels go, indeed if would be ideal if a placeholder would be set by default if none has been provided, I tried that before, but unfortunately the input element will be generated _before_ the label element, and the default text for a label will only be generated at that point.

So automatically setting a placeholder would currently only be possible when the user explicitly provides the label text via the `label` option, that is unless we would reimplement how labels are being automatically generated from the fieldname, so that we could do that before inputs are being generated. Not a big of fan of that, but if there's no other good way, then maybe we can resort to that. I'll have to think about it again.

**Comment by gerhard-lechner** [comment]
Sounds great @ configurable gutter/margin.

I get the problem with the placeholder. I don't rely on automatically created labels and always set a custom label text in the system I'm working on (in fact in my wrapper class I have the `label` option set to `false` if no label text is provided), hence I didn't see this obstacle.

Despite the challenges you mentioned I guess it would make sense to automatically have the `placeholder` set if it isn't already defined in the `$options` array, so thank you for considering it.

**Comment by umer936** [comment]
Does this seem good to add a stable release for it? I've been using it and haven't found specific issues.

**Comment by ndm2** [comment]
There wasn't really feedback for the spacing config feature, but I've gone ahead and merged it. I'll test the current state in a few apps, and if I don't find anything and no one objects, I'll tag a stable release.

**Comment by ndm2** [comment]
I might try to squeeze in a fix for the floating label placeholder "problem" if I can figure something better now, but that would really be the last change then before the stable release 😬

**Comment by ndm2** [comment]
[**4.0.0 has been released**](https://github.com/FriendsOfCake/bootstrap-ui/releases/tag/4.0.0), so let's finally close this. For further issues, please open new tickets.
