### ISSUE TITLE
Option 'append' fails with value '%'

### ISSUE THREAD

**Issue by gameiqinc** [FriendsOfCake/bootstrap-ui#35]
The following code generates a warning:
```
echo $this->Form->input('field', ['append' => '%']);
```

This is the warning:
```
Warning (2): vsprintf(): Too few arguments [CORE\src\View\StringTemplate.php, line 216]
```

Possible solution: Escape % characters before passing strings to vsprintf()

**Comment by gameiqinc** [comment]
Forgot to add. A quick workaround is this:

```
echo $this->Form->input('field', ['append' => '%%']);
```

**Comment by ADmad** [comment]
Since `%` is used in placeholders in `vsprintf()` it needs to be escaped.
