### ISSUE TITLE
bs5 branch button group render issue

### ISSUE THREAD

**Issue by wilsmex** [FriendsOfCake/bootstrap-ui#353]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* BootstrapUI Version: BS5 branch
* Bootstrap Framework Version: 5.0.2

### What you did
```
					$button = $this->Form->button('Button Text', [
						'type' => 'button',
					]);
					echo $this->Form->control('someField', array(
						'append' => [
							$button,
							['type' => 'text']
						]
					));

```

The 'append/prepend' button groups don't render correct (have rounded edge instead of square 'docked' to side of input when using the 'button group' : https://getbootstrap.com/docs/5.0/forms/input-group/#button-addons

When buttons are used, no wrapping 'input-group-append' container is needed.  Actually It seems the only time a wrapping container around the appended/prepended item is needed is if is just plain 'text' from I can tell.

I tried to do a PR, put couldn't work through all the templates etc. as I'm new to this plugin.  Maybe use the 2nd options parameter of the append values array and if there is 'type=>'text' then wrap, otherwise don't add a wrapper?

**Comment by ndm2** [comment]
This is already fixed but not yet merged.

![image](https://user-images.githubusercontent.com/5031606/125899136-0587061f-40fa-4c0a-939a-bb7a992eace3.png)


You can check out [**this pull request**](https://github.com/FriendsOfCake/bootstrap-ui/pull/350) for what's to come. If you want to test it in your project you can alias the repository and require my working branch.

```bash
composer config repositories.bui vcs https://github.com/ndm2/bootstrap-ui
composer require friendsofcake/bootstrap-ui:dev-bs5-support
```

**Comment by ndm2** [comment]
Closing now that preliminary BS5 support has been merged. You can now directly require the `dev-bs5` branch, respectively a pre-release tag once published.
