### ISSUE TITLE
Add helpers for Cards/Modal/etc

### ISSUE THREAD

**Issue by umer936** [FriendsOfCake/bootstrap-ui#374]
This is a (multiple allowed):
* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* BootstrapUI Version: 4.0.0
* Bootstrap Framework Version: 5.1.3
* jQuery: N/A
* Platform and Target: N/A

I often use Bootstrap panels/cards in my CakePHP applications and I stumbled upon: 
https://github.com/CakePHP-Bootstrap/cakephp4-bootstrap-helpers/tree/v4.x/src/View/Helper

The CardHelper seems particularly appealing to me. 

Potentially some of the other Helpers written by CakePHP-Bootstrap can be ported into this one. I have created a similar feature-discussion on that repository (https://github.com/CakePHP-Bootstrap/cakephp4-bootstrap-helpers/issues/8) to see what that repository thinks about merging the missing helpers to here.

**Comment by ndm2** [comment]
I'm not going to stop anyone who wants to add such functionality 😛

**Comment by dereuromark** [comment]
Same for tabs IMO - https://getbootstrap.com/docs/4.4/components/navs/#tab

**Comment by ADmad** [comment]
PRs welcome
