### ISSUE TITLE
Bootstrap-ui form-helper is adding form-group class to controls

### ISSUE THREAD

**Issue by schackochandsi** [FriendsOfCake/bootstrap-ui#378]
* BootstrapUI Version: 4
* Bootstrap Framework Version: 5

 The classes form-group, form-row, and form-inline are removed in Bootstrap 5. But why FriendsOfCake/bootstrap-ui form-helper is adding form-group class to controls?

**Comment by ndm2** [comment]
There should be no `form-row`, only `row`, which is used by BS5.

[**`form-group` and `form-inline` were kept**](https://github.com/FriendsOfCake/bootstrap-ui/issues/349) for versatility reasons, as to make it easier for people to add custom styling. You can ignore them if you don't have any use for them.

**Comment by schackochandsi** [comment]
Good to know! Thank you for the quick response.
