### ISSUE TITLE
add content at end of control

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/bootstrap-ui#383]
Hi,

I want to add content at the end of a form control. eg another hidden input. I can use the help option but then it will be inside the small container. Is there another option I am overlooking?

**Comment by tgoeminne** [comment]
hi any reply on this I am trying to figure out how this plugin works but have hard time fixing it..

$templates = [
                'inputGroupContainer' =>'<div{{attrs}}>{{prepend}}{{content}}{{append}}{{extra}}</div>',
                'extra' => '{{content}}',
            ];

I am using this but with no luck all that happen is the extra 

echo $this->Form->control('name', ['label' => 'Name', 'extra' => 'how are you doing?' , 'templates' => $templates]);

expected result:

<div><input> how are you doing? </div>

actual

<div><input extra="how are you doing"></div>

Can tell me what I am doing wrong here?

greets,
Thomas

**Comment by ndm2** [comment]
You cannot add custom templates like that, the underlying string template functionality provided by CakePHP doesn't support that. What you _can_ do however is adding template variables:

```php
$this->Form->setTemplates([
    'inputContainer' =>
        '<div{{containerAttrs}} ' .
            'class="{{containerClass}}form-group {{type}}{{required}}">{{content}}{{help}}{{extra}}</div>',

    'inputContainerError' =>
        '<div{{containerAttrs}} ' .
            'class="{{containerClass}}form-group {{formGroupPosition}}{{type}}{{required}} is-invalid">' .
                '{{content}}{{error}}{{help}}{{extra}}</div>',
]);

// ...

echo $this->Form->control('name', [
    'label' => 'Name',
    'templateVars' => [
        'extra' => 'how are you doing?'
    ],
]);
```

* **https://book.cakephp.org/4/en/views/helpers/form.html#customizing-the-templates-formhelper-uses**
* **https://book.cakephp.org/4/en/views/helpers/form.html#adding-additional-template-variables-to-templates**

**Comment by tgoeminne** [comment]
thanks, will take a look at that
