### ISSUE TITLE
Nothing fetch "tb_sidebar"

### ISSUE THREAD

**Issue by kenixi** [FriendsOfCake/bootstrap-ui#39]
The baked Template has ```tb_sidebar``` area, But BootstrapUI has no ```$this->start('tb_sidebar');```. So we must add this own. And we must add css for this parts.

Should you add this to default ?

Please think this problem.

**Comment by ADmad** [comment]
The `tb_sider` block is fetched in the example [dashboard](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/Template/Layout/examples/dashboard.ctp) layout provided. But I agree it should be fetched and echoed at appropriate location in the default layout too.

**Comment by ADmad** [comment]
Would you like to provide a pull request to fix this?

**Comment by ADmad** [comment]
Actually `index.ctp` which assigns `tb_sider` does [extend](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/Template/Bake/Template/index.ctp#L6) layout. So can you please elaborate what problem are you having.

**Comment by kenixi** [comment]
Woops!!
I missed and using another file copy. I confirm correct file. I'm sorry about that.
