### ISSUE TITLE
overwrite flash template

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/bootstrap-ui#398]
Hi,

I was wonder where I am supposed to overwrite the flash template? I have tried the following

templates > element > flash > default
templates > plugin > BootstrapUI > flash > default

Both did not work. The only thing I could do was change the code in vendor folder. Which is not what I would want to do.

**Comment by ADmad** [comment]
`templates/plugins/BootstrapUI/element/flash/default.php`
