### ISSUE TITLE
Packagist version not updating?

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/bootstrap-ui#4]
I just noticed the [packagist](https://packagist.org/packages/friendsofcake/bootstrap-ui) version is pointing at an outdated version. Could it be the update hook is not active?

**Comment by AD7six** [comment]
I think the project needs deleting and recreating on packagist. it's not owned by the foc user.

Probably (don't know) the change of owner on github has invalidated the token for the webhook.

@jadb can you coordinate deleting friendsofcake/bootstrap-ui from packagist and having me/admad/jose(either)/jippi/probably many others recreate it under the foc account? Alternatively it might be sufficient to add Foc as a maintainer.

**Comment by jadb** [comment]
Fixed now with @lorenzo, weird behaviour - had to re-paste the same token again in Github.
