### ISSUE TITLE
Pagenate design is correct?

### ISSUE THREAD

**Issue by kenixi** [FriendsOfCake/bootstrap-ui#40]
I try dashboard theme in my app. But pagination design like below. (Out of alignment)

![2015-04-08 17 32 07](https://cloud.githubusercontent.com/assets/6150296/7041557/3cba98c8-de15-11e4-9213-2088c978a0d5.png)

Is this  my mistake or default design? I use default dashboard theme and default baked template.

My ```index.ctp``` code is below.
```html
<div class="paginator">
    <ul class="pagination">
        <?= $this->Paginator->prev('< ' . __('previous')) ?>
        <?= $this->Paginator->numbers() ?>
        <?= $this->Paginator->next(__('next') . ' >') ?>
    </ul>
    <p><?= $this->Paginator->counter() ?></p>
</div>
```

Chrome, firefox, safari are same.

**Comment by kenixi** [comment]
The ```PaginatorHelper.php``` > ```function numbers()``` added ul tag.
But ul tag is not necessary in this case.

Please tell your idea.

**Comment by jadb** [comment]
I will give it a shot.

**Comment by ADmad** [comment]
@kenixi BUI adds extra options to `numbers()` method for generating previous and next links too without without extra methods calls. Check #41.

**Comment by davidyell** [comment]
I just hit this issue as well. It's a shame that it's not compatible with the default baked markup.

**Comment by ADmad** [comment]
I too am not happy with this. We should not deviate from core API as far as possible.

**Comment by jadb** [comment]
Are you guys suggesting we drop the 'prev' and 'next' support from `numbers()`? 

I would love to have those bake templates finished since those would cover not only pagination but other stuff as well (tables, menu, action links, etc.).

**Comment by ADmad** [comment]
@jadb The 'prev', 'next' options can stay but by default `numbers()` should not return the HTML with the wrapping`<ul>` tag, as most users don't expect it. Even I faced the exact same "problem" the first time if used the method.
