### ISSUE TITLE
Multi checkbox in cake5 / BS5

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#400]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)

* BootstrapUI Version: 5.0.1
* Bootstrap Framework Version: 5.3.2

### What you did
https://sandbox.dereuromark.de/sandbox/tools-examples/bitmasks

### Expected Behavior
Multi checkboxes are visible to be clicked.

### Actual Behavior
They seem to be not visible or very difficult to toggle right now

Is that just me or is there sth wrong with the classes being added etc?

![Screenshot from 2024-01-04 21-10-33](https://github.com/FriendsOfCake/bootstrap-ui/assets/39854/700059ea-e710-46f3-b5f0-a0f0155a7303)

**Comment by ndm2** [comment]
Problem is right there:

![image](https://github.com/FriendsOfCake/bootstrap-ui/assets/5031606/6412f1ab-14e6-48ec-bf1e-9d050f72ad49)

**Comment by dereuromark** [comment]
Weird, that didnt cause any issues with previous bootstrap versions
But thx a lot, seems that clears it up, this is not a plugin issue.
