### ISSUE TITLE
Duplicate script name "stan-setup" in composer .json

### ISSUE THREAD

**Issue by per2mn** [FriendsOfCake/bootstrap-ui#401]
- [x] bug

* BootstrapUI Version: master (5.0.1).

### Actual
Duplicate script name "stan-setup" in composer .json
        "**stan-setup**": "cp composer.json composer.backup && composer require --dev phpstan/phpstan:^1.0.0 && mv composer.backup composer.json",
        "**stan-setup**": "phpstan analyze"

### Expected Behavior
Something like
        "stan-setup": "cp composer.json composer.backup && composer require --dev phpstan/phpstan:^1.0.0 && mv composer.backup composer.json",
        "**stan-analyze**": "phpstan analyze"    OR      "**stan**": "phpstan analyze"

**Comment by dereuromark** [comment]
https://github.com/FriendsOfCake/bootstrap-ui/commit/a812fc630e7f7bf4481f7464e5060c4cb00d694c

Thank you!
