### ISSUE TITLE
Call to undefined method BootstrapUI\View\Helper\FlashHelper::success()

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/bootstrap-ui#407]
I am following this piece of documentation:

https://github.com/FriendsOfCake/bootstrap-ui/blob/bd656983263adfee9888f7539bb4afa030659f13/README.md?plain=1#L840

I am getting:

> Call to undefined method BootstrapUI\View\Helper\FlashHelper::success()

Am I doing something wrong? Should I somehow initiate the `FlashHelper` beforehand?

**Comment by ADmad** [comment]
> You can set Flash Messages using the default Flash **component** syntax

**component** not helper.
