### ISSUE TITLE
Optionally load css and js from CDN in default layout?

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/bootstrap-ui#42]
I just started testing and I think it would be nice if the default layout has some sort of condition that, when set, downloads the default css and js  from cdn.

This way new users can quickly get up and running with nice visuals without manually having to setup these assets first.

If this sounds reasonable I will create a PR, suggestion on where to set the option would be appreciated.

**Comment by ADmad** [comment]
One issue with using CDN links is we would have keep updating the version number every time there's a new release for a lib. I personally don't want to deal with that.

**Comment by jadb** [comment]
@ADmad that's a very valid point.

@bravo-kernel was suggesting making it optionally turned off. I would suggest making it optionally turned on by defining a CDN URL to use and in the docs on how to install/activate plugin, provide a default one for the ones that don't want to use bower.

Thoughts?

**Comment by bravo-kernel** [comment]
Making it optional would make me just as happy and even though @ADmad has a point I believe the (adoption and quickstart) gains win over impact here:

+ nothing should break if an older lib version is still being used
+ updating two lib references ([css](//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css) and [javascript](//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js)) seems doable compared to e.g. changing layouts

**Comment by jadb** [comment]
How would it be managed? Right now, there are no 'boostrap.php' configuration required and if we could keep it this way, it is better, otherwise it looses from its 'transparency'.

So maybe in the `HelperHelper` configuration?

**Comment by bravo-kernel** [comment]
Closing as I seem to stand alone in this feature but it feels like a missed opportunity from a marketability standpoint (so effectively applied by "other frameworks").

I already imagined the 1-minute video with that much needed "omg, look how easy, let's get that" factor.

To be honest, it just doesn't look as good with the manual editing :wink:

**Comment by jadb** [comment]
You might be right, but it's a thin line between promoting good practices and catering for laziness.

I can accept an alternative layout one could use that could include the hardcoded CDN assets' paths, if that solves it for lazies ;)

**Comment by bravo-kernel** [comment]
Almost entirely duplicating an alternative layout seems a bit non-dry and even more high-maintenance to me but... since this is indeed a very thin line and I personally don't need the turn-key/lazy solution let's not dwell on this any longer.

Maybe somewhere in the future
