### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by makamo** [FriendsOfCake/bootstrap-ui#43]
I have an Error when i pass to cake 3.1 

 Error: Unsupported operand types 
File /var/www/timesheets/vendor/friendsofcake/bootstrap-ui/src/View/Helper/FlashHelper.php 
Line: 55

**Comment by ADmad** [comment]
Closing in favor of PR

**Comment by ADmad** [comment]
@makamo This issue has been resolved. #47 provided more detailed info which helped figure out the problem make proper fix.
