### ISSUE TITLE
BootstrapUI.FlashHelper + Crud flash system

### ISSUE THREAD

**Issue by adayth** [FriendsOfCake/bootstrap-ui#52]
I can't use BootstrapUI FlashHelper along with Crud flash messages.
Maybe is more an issue of Crud plugin, but with this change plugin should work out of the oven after installing them with composer.

```
if (is_array($flash['params']['class'])) {
    $flash['params']['class'][] = 'alert-' . $class;
}
```

```
if (is_array($flash['params']['class'])) {
    $flash['params']['class'][] = 'alert-' . $class;
} else {
    $flash['params']['class'] = 'alert alert-' . $class;
}
```

**Comment by ADmad** [comment]
Add following event callback in your `AppController::beforeFilter()`:

```php
        $this->Crud->on('setFlash', function (Event $event) {
            unset($event->subject->params['class']);
            $event->subject->element = ltrim($event->subject->type);
        });
``

**Comment by adayth** [comment]
I think that could be a good if friends of cake plugins work well together without to much work.
I don't know if is better to change this plugin or Crud but the issue is that I had actions without Crud that integrate perfectly without extra work with BootstrapUI and Crud actions, with this "problem" that can be fixed with the unset (I did it that way before posting this here)

Please, forgive me if I'm being annoying. I don't want to be a bother you with my stupid issues, just trying to contribute to your fantastic plugins ;)

**Comment by CodeBlastr** [comment]
I agree with adayth.

**Comment by josegonzalez** [comment]
@CodeBlastr would you be willing to submit a pr for this?
