### ISSUE TITLE
Inline / Horizontal Forms

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/bootstrap-ui#54]
http://getbootstrap.com/css/#forms-inline

Looks like generating `class="form-horizontal"` should in fact be `class="form-inline"` for Bootstrap 3.

**Comment by dakota** [comment]
Horizontal forms (http://getbootstrap.com/css/#forms-horizontal) are different than inline forms (http://getbootstrap.com/css/#forms-inline). BootstrapUI is in fact generating the correct class for horizontal forms.

**Comment by davidyell** [comment]
Haha, whoops. Thanks for the correction.
