### ISSUE TITLE
Relations between Tables does not work.

### ISSUE THREAD

**Issue by hantsy** [FriendsOfCake/bootstrap-ui#56]
I created a CakePHP 3 project and use this plugin to replace UI with Bootstrap for official Blog tutorial .

[https://github.com/hantsy/cakephp3-sample](https://github.com/hantsy/cakephp3-sample)

But the the relations Article->Category does not work as expected.

**Comment by jadb** [comment]
Sorry, this is not a support forum.

Furthermore, this does not seem related to the plugin in any way. This plugin merely handles view layer stuff, not model.
