### ISSUE TITLE
How do I properly install this?

### ISSUE THREAD

**Issue by emmandev** [FriendsOfCake/bootstrap-ui#59]
Hi, I'm new to CakePHP. I've followed the instructions, but I don't have the proper layout. I've copied the layouts from your examples folder and transferred them to src/Template/Layout/TwitterBootstrap, and extended a view to try it out but the layout did not change. I also tried to replace CakePHP's ../Layout/default.ctp with bootstrap-ui's default.ctp and still nothing. What am I missing?

Edit: also when I inspect element, it looks right, as it uses the bootstrap's style sheet and script, along with Jquery's.

**Comment by jadb** [comment]
The default layout assumes you have the CSS and JS assets installed. Before using the example layouts, make sure you get the default one working.

If you are using bower, instructions are included in README for installing the assets. 

Another alternative would be to replace the cake app default layout by the one included in the plugin, but make sure you comment out the `public $layout = 'BootstrapUI.default';` line in AppView. You will also need to change the assets' paths to CDN or wherever you have them installed.

**Comment by emmandev** [comment]
I have solved the problem. I already had it installed, the CSS and JS assets. The problem was where bootstrap-ui is looking for them. It looks at myapp/webroot/css/bootstrap/bootstrap.css when I had it at myapp/webroot/css/bootstrap.css. I just had to edit the extra path out, then it works!

Thanks
