### ISSUE TITLE
How can I use alerts/elements?

### ISSUE THREAD

**Issue by emmandev** [FriendsOfCake/bootstrap-ui#60]
1. For example if a user logs in with invalid credentials, it should output an alert box stating the error. Or when a client is not authorized in a specific page. 

2. Or its client side validation?

**Comment by ADmad** [comment]
Please refer to CakPHP manual how to show alert messages using `FlashComponent`. This plugin provides nothing special for that. All it does is style the alert boxes with bootstrap's css.

**Comment by emmandev** [comment]
So I don't have to copy/move anything?
