### ISSUE TITLE
Table::initialize() is not calling parent in baked table classes.

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/bootstrap-ui#63]
Well, the title says it all. :)

**Comment by lorenzo** [comment]
Any reason why it should do that?

**Comment by lorenzo** [comment]
and... is this the actually repo you intended to report the issue?

**Comment by burzum** [comment]
@lorenzo Yes because this is the template I've baked.

My tables should call the parent because I'm extending my AppTable.

I could ask the same question, why is the parent *not* called by default? By experience this will bite you some time in the future when you change the parent for some reason.

**Comment by lorenzo** [comment]
This plugin does not bake table templates, you can open this same ticket in Bake

**Comment by burzum** [comment]
@lorenzo True, thought this gets baked based on the plugins templates as well.
