### ISSUE TITLE
Bootstrap fonts cannot be found.

### ISSUE THREAD

**Issue by vaughany** [FriendsOfCake/bootstrap-ui#67]
I'm just following the instructions in the section 'A quick way of getting the Bootstrap assets installed is using bower.'. I've made a little script from the given code and run it, but quickly noticed that the glyphicons fonts are 404ing. The script makes no note of them (and adding in a line to copy them over is trivial), but I notice that the path given to the fonts in Chrome's Developer Tools is as follows:

```
Failed to load resource: the server responded with a status of 404 (Not Found)

http://192.168.0.100/cakephp3/css/fonts/glyphicons-halflings-regular.woff
```

(...and the same for the other two font files.)

It's looking for the fonts in the wrong place, as the path is hard-coded in the `bootstrap.css` file:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  ...
}
```

I don't have a solution to this at the moment but thought I had better report it.

**Comment by martonmiklos** [comment]
The fonts assets needs to be copied to the webroot directory. 
This commit adds the instruction to the Readme.md. 
https://github.com/martonmiklos/bootstrap-ui/commit/a784bb77e280c74b6843d66254e1923c1a1e9460

**Comment by davidyell** [comment]
I would recommend a symlink rather than copying.

**Comment by jadb** [comment]
I do symlinks as @davidyell suggested but that doesn't work on Windows. Until a better alternative is found maybe in #114, that's the officially proposed ways of doing it.
