### ISSUE TITLE
Helper class could not be found

### ISSUE THREAD

**Issue by sdanko** [FriendsOfCake/bootstrap-ui#68]
When loading helpers in View\AppView I get the following error:
Fatal error: [Cake\View\Exception\MissingHelperException] Helper class HtmlHelper could not be found

**Comment by josegonzalez** [comment]
Can you gist your `AppView` class?

**Comment by sdanko** [comment]
https://gist.github.com/sdanko/f46714ff050bae793e91

**Comment by dereuromark** [comment]
Sure you loaded the plugin correctly?

**Comment by sdanko** [comment]
I addes this line to my bootstrap.php:

<code>
Plugin::load('BootstrapUI');
</code>

**Comment by jadb** [comment]
Did you install the plugin using composer?

**Comment by sdanko** [comment]
Yes, I used the command :
<code>
composer require friendsofcake/bootstrap-ui:~0.3
</code>
in the root folder of my app.

**Comment by sdanko** [comment]
Any ideas?

**Comment by sillentkil** [comment]
Hi,
I have the same problemen, did u get it working ?

**Comment by ayman-alkom** [comment]
Hi @sillentkil 
for testing your issue I have tried a fresh copy as following:

    composer create-project --prefer-dist cakephp/app bookmarker
    cd bookmarker
    composer require friendsofcake/bootstrap-ui
    update the src\View\AppView.php as in https://gist.github.com/sdanko/f46714ff050bae793e91
    "bin/cake" server
    go to http://localhost:8765/

every thing is OK

**Comment by sillentkil** [comment]
Weird, i did the following:
composer create-project --prefer-dist cakephp/app
composer require friendsofcake/bootstrap-ui
update the src\View\AppView.php

and getting the following error: http://cosmicancestors.ritepro.nl/

What is the "bin/cake" server part? 


Many thanks,
Ricardo

**Comment by ayman-alkom** [comment]
`"bin/cake" server` is just to run a local testing server

**Comment by ADmad** [comment]
@sillentkil What's your PHP version?

**Comment by sillentkil** [comment]
i'm using PHP 5.5.9-1 ubuntu 4.11

**Comment by sillentkil** [comment]
Ok i think i got it working, i used composer create-project --prefer-dist cakephp/app bookmarker and that is working. 

when i use it  without bookmarker it is not working. and i get the errors

**Comment by sillentkil** [comment]
Ok just to confirm when i do the following:
composer create-project --prefer-dist cakephp/app {project name}
It is working
when i do composer create-project --prefer-dist cakephp/app
it is not, maby its a bug in cake but thanks helping me out.

**Comment by ayman-alkom** [comment]
I am happy to know that your problem got out. @sillentkil  :+1:

**Comment by YuvPrime** [comment]
I'm facing the same issue in recent Cakephp & this library version.

**Comment by jadb** [comment]
@YuvPrime how did you install? Using composer or download? Did you load the plugin in `config/bootstrap.php`? Have you followed the instructions in README?

**Comment by martinslae** [comment]
Eu estava com mesmo o problema e era porque no windows funcionava com $this->html->script mas como o linux é casesensitive não funcionava.

tive que alterar na view de $this->**h**tml->script para $this->**H**tml->script

**Comment by jadb** [comment]
Sorry, english please.

**Comment by shu845** [comment]
Thank you @martinslae. I don't understand his language, but as he says, I changed "$this->**h**tml->script" to "$this->**H**tml->script" in all .ctp files and the error disappeared.
