### ISSUE TITLE
Responsive nav bar header

### ISSUE THREAD

**Issue by ayman-alkom** [FriendsOfCake/bootstrap-ui#69]
the bootstrap side menu go hidden in small screen sizes.
and we have the header nav bar but empty.
I thought we can grape the side bar items to it.
If you are agree I can make a pull request for this.

we can add them as a sub menu inside a main item in the header nav

![screencapture-kobitmobil-com-apps-maras-categories-add-1435662901190](https://cloud.githubusercontent.com/assets/2862528/8429656/8d3ae132-1f32-11e5-90c4-e957aea162e0.png)

**Comment by jadb** [comment]
You mean the CrudView sidebar?

**Comment by ayman-alkom** [comment]
I mean the bake `src/Template/Bake/Template/index.ctp` side bar (`tb_sidebar `block)
 and the layout `/src/Template/Layout/examples/dashboard.ctp`  (`navbar-collapse collapse`)
I wonder if that is a part of the plugin, or not.

**Comment by jadb** [comment]
It's a sample, not really part of the plugin (more than being included). The fact is that people want to use their own markup sometimes but I can totally see this beneficial to the ones sticking to re-using the examples (me included). Go ahead with the PR!

**Comment by ayman-alkom** [comment]
ok
