### ISSUE TITLE
Add form (validation) feedback

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/bootstrap-ui#7]
As requested. Please consider implementing these additions so generated forms will support validation feedback out-of-the-box.
# Feedback icons

To add <em>optional feedback icons</em> support the "has-feedback" class has to be added to (only the) textual input elements with class "form-control".
### Vertical

HTML example from the Bootstrap 3 page:

```
<div class="form-group has-success has-feedback">
  <label class="control-label" for="inputSuccess2">Input with success</label>
  <input type="text" class="form-control" id="inputSuccess2" aria-describedby="inputSuccess2Status">
  <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
  <span id="inputSuccess2Status" class="sr-only">(success)</span>
</div>
```

Working CakePHP generated example:

```
<div class="form-group has-error has-feedback">
    <label class="control-label" for="url">Url</label>
    <input name="url" required="required" id="url" class="form-control" type="text">
    <span class="fa fa-times form-control-feedback" aria-hidden="true"></span>
</div>
```

Produces something like this:

![bsui-feedback-vertical](https://cloud.githubusercontent.com/assets/230500/5726858/0020347a-9b5f-11e4-954d-6725d94a65f4.png)

> please note: that checkbox should not have the "has-feedback" class.
### Horizontal

The horizontal form needs a slightly different layout, as shown in the Bootstrap code below:

```
  <div class="form-group has-success has-feedback">
    <label class="control-label col-sm-3" for="inputSuccess3">Input with success</label>
    <div class="col-sm-9">
      <input type="text" class="form-control" id="inputSuccess3" aria-describedby="inputSuccess3Status">
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
      <span id="inputSuccess3Status" class="sr-only">(success)</span>
    </div>
  </div>
```

Currently generated CakePHP code:

```
<div class="form-group has-feedback has-error">
    <label class="control-label col-md-2" for="url">Url</label>
    <div class="col-md-10">
        <input name="url" required="required" id="url" class="form-control" type="text">
    </div>
    <span class="fa fa-times form-control-feedback" aria-hidden="true"></span>
</div>
```

Now produces something like: 

![bsui-feedback-horizontal](https://cloud.githubusercontent.com/assets/230500/5726611/10197b9a-9b5d-11e4-89c3-a35e3feee99f.png)
# Help block

In the images above the Bootstrap "help-block" span element is used to display the validation messages. I think adding an empty span by default would be a nice addition too (so they only have to be filled using JS, not created).
### Vertical

Working CakePHP generated example:

```
<div class="form-group has-error has-feedback">
    <label class="control-label" for="url">Url</label>
    <input name="url" required="required" id="url" class="form-control" type="text">
    <span class="fa fa-times form-control-feedback" aria-hidden="true"></span>
    <span class="help-block">
        <ul class="list-unstyled">
            <li>A minimum of 10 characters is required</li>
            <li>A valid email address is required</li>
        </ul>
    </span>
</div>
```
### Horizontal

Currently generated Cake code::

```
<div class="form-group has-feedback has-error">
    <label class="control-label col-md-2" for="url">Url</label>
    <div class="col-md-10">
        <input name="url" required="required" id="url" class="form-control" type="text">
    </div>
    <span class="fa fa-times form-control-feedback" aria-hidden="true"></span>
    <span class="help-block">
        <ul class="list-unstyled">
            <li>A minimum of 10 characters is required</li>
            <li>A valid email address is required</li>
        </ul>
    </span>
</div>
```
# Horizontal checkbox

The horizontal checkbox is not generated as shown on the Bootstrap pages.

This could be due to the generated html but.... somehow removing the form-control class also seems to solve the issue.

Bootstrap example code:

```
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
```

Currently generated Cake code:

```
<div class="form-group has-feedback">
    <div class="col-md-offset-2 col-md-10">
        <input name="force" value="0" type="hidden">
        <label for="force">
            <input name="force" value="1" id="force" class="form-control" type="checkbox">Force
        </label>
    </div>
</div>
```

**Comment by jadb** [comment]
Thanks for this great overview. I will definitely be looking into it ASAP.

**Comment by bravo-kernel** [comment]
No rush and no thanks... I have come to the conclusion that it's much more efficient to spend time on describing the issue than wasting it on failed PR attempts ;)

**Comment by dereuromark** [comment]
I like the idea - whats the status on this so far?

**Comment by bravo-kernel** [comment]
As far as myself is concerned, I am a bit busy working on other things so I haven not (even) started work on this.

**Comment by jadb** [comment]
I think this should now be doable using some javascript with the new markup that 0.3 spits out.

The mis-aligned help block should now be fixed too (a new option `help` was added to `Form::input()`) and checkboxes/radio buttons use a different container markup than inputs (so has-feedback, when injected using JS should not appear for them). 

That been said, I have not tested it, as this is only a PHP plugin,  but I am assuming that one might run with issues for other types like `select`, `textarea`, etc.; and I am not sure I want this plugin to do everything for the end-user (after all, there would be maintenance involved).

**Comment by jadb** [comment]
@bravo-kernel - 0.3 will be out soon and like I said in my previous comment, this should now be doable using javascript given the new markup enhancements made.

I have attempted adding this feature without bloating the code and for now, I still don't have a solution I am pleased with. For the time being, it's been moved to 0.4.

If the javascript solution works, I'd rather just add that to the documentation. 

Let me know if you test it and how well it works out.

**Comment by bravo-kernel** [comment]
Hey @jadb, thanks for updating, highly appreciated. I have seen a lot of progress and will:

+ give it another shot as soon as I can find some time
+ update this issue with a stripped down version given the current state

**Comment by mohinlakdawala** [comment]
Any updates on this will be highly appreciated. Its a very good idea.

**Comment by jadb** [comment]
ping @bravo-kernel

**Comment by bravo-kernel** [comment]
Since I have abandoned front-end development completely I will not be able to contribute to this (forgotten) issue any longer.

**Comment by dereuromark** [comment]
I guess we can then also close these very old ones.
