### ISSUE TITLE
Helpers not loading if using Ajax if configured in AppView::initialize()

### ISSUE THREAD

**Issue by icaroscherma** [FriendsOfCake/bootstrap-ui#71]
Bootstrap-UI is working flawlessly with me, except when I use ajax, for instance Ajax Pagination.

__Why am I saying this?__ Because if I set a paginator template it will work when the page is first rendered, but in the following ones I get the default template. The same happens with ``BootstrapUI.Form`` (if there are forms inside the pagination).

I noticed that the ajax is ignoring the ``$this->loadHelper();`` instanced in ``AppView::initialize()``.
But if I manually set ``public $helpers`` into the ``AppController`` they will load. So seems that it is not merging into the default configuration, or am I missing something?

I know that this is a CakePHP 3 related question, not a Bootstrap-UI but since I think that other users may also have the same question.

Later I will add the answer to the main CakePHP 3 Docs.

**Comment by lorenzo** [comment]
How does your `AjaxView` class look like?

**Comment by icaroscherma** [comment]
I haven't created ``App\AjaxView`` or changed ``Cake\AjaxView``, but since rest of the content loads ok, I thought that ``AppView`` would "figure this out".

After what you said, I looked into the ``Cake\AjaxView`` file and there is no ``initialize()`` but there is a __layout__ definition and a __constructor__ , but isn't supposed to ``AppView`` to merge with global / default config?

I'm thinking in creating an ``App\AjaxView`` extending ``Cake\AjaxView`` putting only the ``initialize()`` method with the ``loadHelper()`` methods. Is this the best approach?

**Comment by icaroscherma** [comment]
Yeah... it works using like this:

``App\src\View\AjaxView.php``
```
<?php
namespace App\View;

class AjaxView extends Cake\View\AjaxView
{
	
    public function initialize()
    {
        parent::initialize();
        $this->loadHelper('Html', ['className' => 'BootstrapUI.Html']);
        $this->loadHelper('Form', ['className' => 'BootstrapUI.Form']);
        $this->loadHelper('Flash', ['className' => 'BootstrapUI.Flash']);
        $this->loadHelper(
    		'Paginator',
    		[
    			'className' => 'BootstrapUI.Paginator',
    			'templates' => 'paginator-template'
    		]
    	);
    }
}
```

But I'm not sure if this is the best approach. =x

**Comment by lorenzo** [comment]
It is a good approach. As you can see the `AjaxView` class was recently moved out of the core so it can be tweaked in your app code and can also inherit defaults from `AppView`:

https://github.com/cakephp/app/blob/master/src/View/AjaxView.php
