### ISSUE TITLE
help-block on error invalid html code

### ISSUE THREAD

**Issue by repher** [FriendsOfCake/bootstrap-ui#72]
Hello!

If there are more than one errors on an input field, `FormHelper` puts `<ul>` inside `<p>` which is not valid html5 code. This leads to ugly and problematic thinks like Chrome closing the `<p>` tag automatically before the list and adding another `<p></p>` after the list like this:

```html
<p class="help-block"></p>
<ul>
    <li>This field is required</li>
    <li>Please provide an email address!</li>
</ul>
<p></p>
```

I suggest to replace `<p>` with `<div>` in `$_templates = ['error']` in `FormHelper.php`:
```html
<div class="help-block">
    <ul>
        <li>This field is required</li>
        <li>Please provide an email address!</li>
    </ul>
</div>
```
Bootstrap only defines `.help-block` so this change should not break anything.

Same applies to `help` template.

Bernhard

**Comment by ADmad** [comment]
Closing as PR is opened.
