### ISSUE TITLE
Simple way  to modify the inputContainer for an input?

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/bootstrap-ui#78]
I need to inject attributes to the input container, but the template looks like it won't allow me to do that.

```php
'inputContainer' => '<div class="form-group{{required}}">{{content}}{{help}}</div>',
```

It would be really nice to be able to inject any kind of attributes to any element. Maybe there is a workaround for that? If I could at least do something like in Cake2 `'div' => false` it would allow me to manually wrap the input.

The background is that I need to modify plenty of the markup to use Angular JS directives.

**Comment by ADmad** [comment]
Ability to use arbitrary template vars has been added in Cake 3.1 using 'templateVars' option.
