### ISSUE TITLE
Resolve symlinks

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/bootstrap-ui#8]
The symlinks ( https://github.com/FriendsOfCake/bootstrap-ui/tree/master/src/Template/Element/Flash ) should be resolved using elements.

Otherwise this will break on WIN plattforms.

**Comment by jadb** [comment]
Thanks @dereuromark! Resolved in a063ad42a3f236a2b9950c8614ab4ee8944bba4a.
