### ISSUE TITLE
improve the view.ctp bake file

### ISSUE THREAD

**Issue by ayman-alkom** [FriendsOfCake/bootstrap-ui#82]
I have improved this file in my project ,using a table of two columns to show the keys and values of the item.
I wonder if you are interesting in making a PR of this.

**Comment by jadb** [comment]
@ayman-alkom sorry to have missed this, too many things going on. Submit the PR so we can review it all together.

**Comment by ayman-alkom** [comment]
Ok I will

**Comment by ayman-alkom** [comment]
sorry to be late, the PR is https://github.com/FriendsOfCake/bootstrap-ui/pull/95

**Comment by dereuromark** [comment]
Can be closed then?
