### ISSUE TITLE
Unnecessary {{type}} class

### ISSUE THREAD

**Issue by steefaan** [FriendsOfCake/bootstrap-ui#83]
Let's discuss first before I create a PR for that. Any `inputContainer` gets an additional class `{{type}}` as you can see here: https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L61

Bootstrap doesn't require this class, so I think it shouldn't be a part of the BootstrapUI plugin. The additional class makes it more complicate to include libraries like https://github.com/flatlogic/awesome-bootstrap-checkbox.

With additional `{{type}}` class:
![image](https://cloud.githubusercontent.com/assets/5982785/9226732/4c3b4dde-4110-11e5-837f-1c9ab9b94038.png)

Without additional `{{type}}` class:
![image](https://cloud.githubusercontent.com/assets/5982785/9226762/705092c4-4110-11e5-8a1a-169b029a4153.png)

For sure I need to override the RadioWidget from BootstrapUI anyways to get this working and sure I can also override the `inputContainer` template but it wouldn't be necessary if we stick to the Bootstrap conventions what the idea of the plugin is I think.

**Comment by ADmad** [comment]
I would prefer keeping the extra type classes. The lib you have linked is probably also adding non-bootstrap classes which is causing the issue. So imo you should resolve the issue by using custom widget / templates.

**Comment by dereuromark** [comment]
Wasn't I the one adding it? I think the type makes styling in some cases easier and in some cases impossible without it if I recall correctly - especially when coming from the core and using this plugin.

**Comment by ayman-alkom** [comment]
I am agree with @dereuromark specially for date input styling

**Comment by jadb** [comment]
I agree with above comments. @steefaan I will close this as I think its fate just got decided but read @ADmad's suggestion and if you do it, I would like those custom stuff added as documentation/examples for people in the future if you don't mind sharing them.
