### ISSUE TITLE
Request for Change on instructed folder structure

### ISSUE THREAD

**Issue by Modicrumb** [FriendsOfCake/bootstrap-ui#86]
So this folder structure is mainly for the files on the plugin users end in the cake webroot folder. Actual file names are inaccurate. The current file structure doesn't allow fonts to work automatically in this bootstrap plug in. CSS code within bootstrap would have to be changed for it to work.

The current folder structure is:
  webroot:
    css:
      bootstrap:
        thecssfile.css
    js:
      bootstrap:
        thebootstrap.js
      jquery:
        jquery.js

A new proposed file structure is:
webroot:
  bootstrap:
    css:
      cssfiles
    js:
      javascripts
    jquery:
      jquery
    fonts:
      fonts
However I realized this problem: people might want to use the bootstrap folder for other things, ex a wordpress blog or something along those lines. If this is an issue then I can see why a file structure like this shouldn't be used/encouraged.

Another possible solution is to just tell them to throw their assets with the others in the webroot folder, IE putting all bootstrap js files in webroot/js rather than throwing files in bootstrap directories, and changing the default template accordingly. I will attach a pull request with the first proposed solution.

Related to issue #67 and Pull Request #88  

 /cc @jadb @ADmad

**Comment by ADmad** [comment]
I not sure what folder structure you are referring to. This plugin does not contain any bootstrap js or css files (only optional example css files). 

So you are free to use whatever folder structure you want in your app. There's no to be done in the plugin itself.

**Comment by ADmad** [comment]
Ah I now see your related PR. Closing this ticket, discussion can be continued on the PR.
