### ISSUE TITLE
FormHelper input inserts multiple class="..." attributes to html element

### ISSUE THREAD

**Issue by sarrala** [FriendsOfCake/bootstrap-ui#91]
When I call:
```
echo $this->Form->input('some.thing', [
		'options' => $input_options,
		'class' => 'testclass'
]);
```

Opening tag looks like this, which confuses at least some browsers (chrome):
```
<select class="form-control" name="some[thing]" class="testclass form-control">
```

And I think that it should look like this:
```
<select name="some[thing]" class="testclass form-control">
```

I think that problem is in `select` template as `StringTemplate::_compiled['select']` contains following:
See [View/Helper/FormHelper.php#L39](https://github.com/FriendsOfCake/bootstrap-ui/blob/master/src/View/Helper/FormHelper.php#L39)
```
<select class="form-control" name="%s"%s>%s</select>
```

And data attrs contains:
```
class="testclass form-control"
```

**Comment by dereuromark** [comment]
Closing as PR is open.
