### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/bootstrap-ui#94]
With 3.1 having been released now and the last official release is 42 commits behind master, it seems logical to push a new release.

Using `0.3.1` with Cake 3.1 causes a Fatal in the FlashHelper.

Using `dev-master` works, but I'd rather use a release as this repo has no `develop` branch, so I can't be guarantee that `master` is stable.

**Comment by ADmad** [comment]
New release done.

**Comment by davidyell** [comment]
Thanks @ADmad
